--- 
javascripts: 
- base: 
  - raphael
  - helpers_shared
  - autocomplete_terms
  - jquery-ui-1.8.6.custom.min
  - jquery.history
  - application
  
- mobile:
    - helpers_shared
    - jquery-ui-1.8.6.custom.min
    - application_mobile
    
stylesheets: 
- gridview: 
    - shared
    - gridview_and_listview
    - gridview
    - jquery-ui-1.8.6.custom
- listview: 
    - shared
    - gridview_and_listview
    - listview
    - jquery-ui-1.8.6.custom
- mobileview: 
    - shared
    - mobile
