--- 
javascripts: 
- base: 
  - raphael
  - helpers
  - application
  - jquery-ui-1.8rc3.custom.min
  - jquery.tablednd_0_5
  - jquery.history
  - facebooksessionops
  - jquery.autocomplete.min
  - autocomplete_terms
stylesheets: 
- base: 
  - camera
  - compare
  - show
  - welcome
