--- 
javascripts: 
- base: 
  - raphael
  - helpers_shared
  - jquery-ui-1.8.6.custom.min
  - jquery.history
  - jquery_galleria
  - galleria.classic
  - jquery.livequery
  - application_old
  
- mobile:
    - helpers_shared
    - jquery-ui-1.8.13.custom.min
    - application_mobile
- bb_loader: 
  - raphael
  - helpers_shared
  - jquery-ui-1.8.13.custom.min
  - jquery.history
  - jquery_galleria
  - galleria.classic
  - application
  - bbfixes
  - jquery.infinitescroll
- loader:
    - loader
stylesheets: 
- assist: 
    - shared
    - assist_and_direct
    - assist
- direct: 
    - shared
    - assist_and_direct
    - direct
- mobileview: 
    - shared
    - mobile
- bb_embed:
    - shared
    - assist_and_direct
    - assist
