--- 
javascripts: 
- base: 
  - raphael
  - helpers_shared
  - autocomplete_terms
  - jquery-ui-1.8.6.custom.min
  - jquery.history
  - jquery_galleria
  - jquery.livequery
  - css_browser_selector
  - application
  
- mobile:
    - helpers_shared
    - jquery-ui-1.8.6.custom.min
    - application_mobile
    
stylesheets: 
- assist: 
    - shared
    - assist_and_direct
    - assist
    - jquery-ui-1.8.6.custom
- direct: 
    - shared
    - assist_and_direct
    - direct
    - jquery-ui-1.8.6.custom
- mobileview: 
    - shared
    - mobile
