--- 
javascripts: 
- base: 
  - raphael
  - helpers_shared
  - helpers
  - application_shared
  - application
  - jquery-ui-1.8.custom.min
  - jquery.tablednd_0_5
  - jquery.history
  - facebooksessionops
  - jquery.autocomplete.min
  - autocomplete_terms
  
- mobile:
    - helpers_shared
    - application_mobile
    - jquery-ui-1.8.custom.min
    
stylesheets: 
- gridview: 
    - shared
    - gridview_and_listview
    - gridview
- listview: 
    - shared
    - gridview_and_listview
    - listview
- mobileview: 
    - shared
    - mobile
