--- 
javascripts:
- mobile:
    - helpers_shared
    - jquery-ui-1.8.13.custom.min
    - application_mobile
- bb_loader: 
  - raphael
  - helpers_shared
  - jquery-ui-1.8.13.custom.min
  - jquery.history
  - application
  - bbfixes
- loader:
    - loader
stylesheets: 
- assist: 
    - shared
    - assist_and_direct
    - assist
- direct: 
    - shared
    - assist_and_direct
    - direct
- mobileview: 
    - shared
    - mobile
- bb_embed:
    - shared
    - assist_and_direct
    - assist
