--- 
javascripts: 
- base: 
  - raphael
  - helpers
  - application
  - supersleight.plugin
  - jquery.tablednd_0_5
  - facebooksessionops
stylesheets: 
- base: 
  - camera
  - compare
  - show
  - welcome
