# c = continuous
# cat = categorical
# b = boolean
# boost = boostexter feature for labels
# show = this causes display in CompareController#show
# showList = for direct view, this causes display in .itemfeatures

####Spaces are required between elements in an array

#######################################
#    Best Buy Demo - Cameras & TVs    #
#######################################

besttv:
    product_type: tv_bestbuy
    layout: assist
    site_id: 12 # See Piwik at analytics.optemo.com for details
    price:
        feature_type: Continuous
        used_for: [filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    maxresolution: 
        feature_type: Continuous
        used_for: [desc, filter, cluster, show]
    screensize:
        feature_type: Continuous
        used_for: [desc, filter, cluster, show]
    power:
        feature_type: Continuous
        used_for: [desc, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [filter, show]
    displaytech:
        feature_type: Categorical
        used_for: [filter, show]

bestbuy:
    product_type: camera_bestbuy
    layout: assist
    site_id: 12 # See Piwik at analytics.optemo.com for details
    price:
        feature_type: Continuous
        used_for: [filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    maxresolution: 
        feature_type: Continuous
        used_for: [desc, filter, cluster, show]
    screensize:
        feature_type: Continuous
        used_for: [desc, filter, cluster, show]
    opticalzoom:
        feature_type: Continuous
        used_for: [desc, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [show, filter, cluster]
    color:
        feature_type: Categorical
        used_for: [show, filter, cluster]

#######################################
#    Cameras.BrowseThenBuy, Mobile    #
#######################################

cameras:
    product_type: camera_us
    layout: assist
    site_id: 10 # See Piwik at analytics.optemo.com for details
    maximumresolution: 
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    displaysize:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [boost, show, filter]

cameras.browsethenbuy.com:
    product_type: camera_us
    layout: assist
    site_id: 4 # See Piwik at analytics.optemo.com for details
    maximumresolution: 
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    displaysize:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]
        
cameras.direct.demo.optemo.com:
    product_type: camera_us
    layout: direct
    site_id: 14 # See Piwik at analytics.optemo.com for details
    maximumresolution: 
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    displaysize:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]        
cameras.direct:
    product_type: camera_us
    layout: direct
    site_id: 10 # See Piwik at analytics.optemo.com for details
    maximumresolution: 
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    displaysize:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]                
cameras.assist.demo.optemo.com:
    product_type: camera_us
    layout: assist
    site_id: 14 # See Piwik at analytics.optemo.com for details
    maximumresolution: 
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    displaysize:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]
cameras.assist:
    product_type: camera_us
    layout: assist
    site_id: 10 # See Piwik at analytics.optemo.com for details
    maximumresolution: 
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    displaysize:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]        
m.demo.optemo.com:
    product_type: camera_us
    layout: mobileview
    site_id: 8 # See Piwik at analytics.optemo.com for details
    maximumresolution: 
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    displaysize:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]

mobile:
    product_type: camera_us
    layout: mobileview
    site_id: 10 # See Piwik at analytics.optemo.com for details
    maximumresolution: 
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    displaysize:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]
        
localhost:
    product_type: camera_bestbuy
    layout: assist
    site_id: 12 # See Piwik at analytics.optemo.com for details
    price:
        feature_type: Continuous
        used_for: [filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    maxresolution: 
        feature_type: Continuous
        used_for: [desc, filter, cluster, show]
    screensize:
        feature_type: Continuous
        used_for: [desc, filter, cluster, show]
    opticalzoom:
        feature_type: Continuous
        used_for: [desc, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [show, filter, cluster]
    color:
        feature_type: Categorical
        used_for: [show, filter]
    waterproof:
        feature_type: Binary
        used_for: [show, filter]
    customerRating:
        feature_type: Continuous
        used_for: [filter]

ilovecameras:
    product_type: camera_bestbuy
    layout: assist
    site_id: 12 # See Piwik at analytics.optemo.com for details
    price:
        feature_type: Continuous
        used_for: [filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    maxresolution: 
        feature_type: Continuous
        used_for: [desc, filter, cluster, show]
    screensize:
        feature_type: Continuous
        used_for: [desc, filter, cluster, show]
    opticalzoom:
        feature_type: Continuous
        used_for: [desc, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [show, filter, cluster]
    color:
        feature_type: Categorical
        used_for: [show, filter]
    waterproof:
        feature_type: Binary
        used_for: [show, filter]
        
ilovecameras.optemo.com:
    product_type: camera_bestbuy
    layout: assist
    site_id: 12 # See Piwik at analytics.optemo.com for details
    price:
        feature_type: Continuous
        used_for: [filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    maxresolution: 
        feature_type: Continuous
        used_for: [desc, filter, cluster, show]
    screensize:
        feature_type: Continuous
        used_for: [desc, filter, cluster, show]
    opticalzoom:
        feature_type: Continuous
        used_for: [desc, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [show, filter, cluster]
    color:
        feature_type: Categorical
        used_for: [show, filter]
    waterproof:
        feature_type: Binary
        used_for: [show, filter]
    customerRatings:
        feature_type: Continuous
        used_for: [filter]

################################
#  LaserPrinterHub, Printers   #
################################

printers.browsethenbuy.com:
    product_type: printer_us
    layout: direct
    site_id: 2 # See Piwik at analytics.optemo.com for details
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        feature_type: Categorical
        used_for: [showList]
    paperinput:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        feature_type: Binary
        used_for: [boost, filter, show]
    scanner:
        feature_type: Binary
        used_for: [boost, filter, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]

printers.direct.demo.optemo.com:
    product_type: printer_us
    layout: direct
    site_id: 16 # See Piwik at analytics.optemo.com for details
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        feature_type: Categorical
        used_for: [showList]
    paperinput:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        feature_type: Binary
        used_for: [boost, filter, show]
    scanner:
        feature_type: Binary
        used_for: [boost, filter, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]
        
printers.direct:
    product_type: printer_us
    layout: direct
    site_id: 10 # See Piwik at analytics.optemo.com for details
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        feature_type: Categorical
        used_for: [showList]
    paperinput:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        feature_type: Binary
        used_for: [boost, filter, show]
    scanner:
        feature_type: Binary
        used_for: [boost, filter, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]        
printers.assist.demo.optemo.com:
    product_type: printer_us
    layout: assist
    site_id: 16 # See Piwik at analytics.optemo.com for details
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        feature_type: Categorical
        used_for: [showList]
    paperinput:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        feature_type: Binary
        used_for: [boost, filter, show]
    scanner:
        feature_type: Binary
        used_for: [boost, filter, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]

printers.assist:
    product_type: printer_us
    layout: assist
    site_id: 10 # See Piwik at analytics.optemo.com for details
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        feature_type: Categorical
        used_for: [showList]
    paperinput:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        feature_type: Binary
        used_for: [boost, filter, show]
    scanner:
        feature_type: Binary
        used_for: [boost, filter, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]

laserprinterhub.com:
    product_type: printer_lph
    layout: assist
    site_id: 6 # See Piwik at analytics.optemo.com for details
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        feature_type: Categorical
        used_for: [showList]
    paperinput:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        feature_type: Binary
        used_for: [boost, filter, show]
    scanner:
        feature_type: Binary
        used_for: [boost, filter, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]
laserprinterhub.ca:
    product_type: printer_lph
    layout: assist
    site_id: 6 # See Piwik at analytics.optemo.com for details
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        feature_type: Categorical
        used_for: [showList]
    paperinput:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        feature_type: Binary
        used_for: [boost, filter, show]
    scanner:
        feature_type: Binary
        used_for: [boost, filter, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]
        
ast0.optemo.com:
    product_type: printer_lph
    layout: assist
    site_id: 6 # See Piwik at analytics.optemo.com for details
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        feature_type: Categorical
        used_for: [showList]
    paperinput:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        feature_type: Binary
        used_for: [boost, filter, show]
    scanner:
        feature_type: Binary
        used_for: [boost, filter, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]

printers:
    product_type: printer_us
    layout: direct
    site_id: 10 # See Piwik at analytics.optemo.com for details
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        feature_type: Categorical
        used_for: [showList]
    paperinput:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        feature_type: Binary
        used_for: [boost, filter, show]
    scanner:
        feature_type: Binary
        used_for: [boost, filter, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]
