# c = continuous
# cat = categorical
# b = boolean
# boost = boostexter feature for labels
# show = this causes display in CompareController#show
# showList = for listview, this causes display in .itemfeatures

####Spaces are required between elements in an array

#######################################
#   Cameras.BrowseThenBuy - Cameras   #
#######################################

cameras:
    product_type:
        - camera_us
    layout:
        - gridview
    maximumresolution: 
        - Continuous
        - [boost, cluster, filter]
    displaysize:
        - Continuous
        - [boost, cluster, filter]
    price:
        - Continuous
        - [boost, cluster, filter]
        - prefdir: -1
    opticalzoom:
        - Continuous
        - [boost, cluster, filter]
    slr:
        - Binary
        - [boost, cluster]
    brand:
        - Categorical
        - [boost, cluster, filter]

cameras.browsethenbuy.com:
    product_type:
        - camera_us
    layout:
        - gridview
    maximumresolution: 
        - Continuous
        - [boost, cluster, filter]
    displaysize:
        - Continuous
        - [boost, cluster, filter]
    price:
        - Continuous
        - [boost, cluster, filter]
        - prefdir: -1
    opticalzoom:
        - Continuous
        - [boost, cluster, filter]
    slr:
        - Binary
        - [boost, cluster]
    brand:
        - Categorical
        - [boost, cluster, filter]

m.browsethenbuy.com:
    product_type:
        - camera_us
    layout:
        - gridview
    maximumresolution: 
        - Continuous
        - [boost, cluster, filter]
    displaysize:
        - Continuous
        - [boost, cluster, filter]
    price:
        - Continuous
        - [boost, cluster, filter]
        - prefdir: -1
    opticalzoom:
        - Continuous
        - [boost, cluster, filter]
    slr:
        - Binary
        - [boost, cluster]
    brand:
        - Categorical
        - [boost, cluster, filter]

################################
#  LaserPrinterHub - Printers  #
################################

printers.browsethenbuy.com:
    product_type:
        - printer_us
    layout:
        - lineview
        - simple
    price:
        - Continuous
        - [boost, cluster, filter, show]
        - prefdir: -1
    ppm:
        - Continuous
        - [boost, cluster, filter, show, showList]
    resolutionmax:
        - Continuous
        - [boost, cluster, filter, show]
    resolution:
        - Categorical
        - [showList]
    paperinput:
        - Continuous
        - [boost, cluster, filter, show, showList]
    itemwidth:
        - Continuous
        - [boost, cluster, filter, show, showList]
        - prefdir: -1
    printserver:
        - Binary
        - [boost, cluster, filter]
    scanner:
        - Binary
        - [boost, cluster, filter]
    brand:
        - Categorical
        - [boost, cluster, filter]
            
laserprinterhub.com:
    product_type:
        - printer_us
    layout:
        - gridview
    price:
        - Continuous
        - [boost, cluster, filter]
        - prefdir: -1
    ppm:
        - Continuous
        - [boost, cluster, filter, showList]
    resolutionmax:
        - Continuous
        - [boost, cluster, filter, showList]
    paperinput:
        - Continuous
        - [boost, cluster, filter, showList]
    itemwidth:
        - Continuous
        - [boost, cluster, filter, showList]
        - prefdir: -1
    printserver:
        - Binary
        - [boost, cluster, filter]
    scanner:
        - Binary
        - [boost, cluster, filter]
    brand:
        - Categorical
        - [boost, cluster, filter]

localhost:
    product_type:
        - printer_us
    layout:
        - gridview
    price:
        - Continuous
        - [boost, cluster, filter]
        - prefdir: -1
    ppm:
        - Continuous
        - [boost, cluster, filter, showList]
    resolutionmax:
        - Continuous
        - [boost, cluster, filter, showList]
    paperinput:
        - Continuous
        - [boost, cluster, filter, showList]
    itemwidth:
        - Continuous
        - [boost, cluster, filter, showList]
        - prefdir: -1
    printserver:
        - Binary
        - [boost, cluster, filter]
    scanner:
        - Binary
        - [boost, cluster, filter]
    brand:
        - Categorical
        - [boost, cluster, filter]

#############################
#  Build Direct - Flooring  #
#############################

builddirect.optemo.com:
    product_type: 
        - flooring_builddirect
    layout:
        - lineview
        - simple
    price:
        - Continuous
        - [boost, cluster, filter, show]
        - prefdir: -1
    width:
        - Continuous
        - [boost, cluster, filter, showList]
        - prefdir: 0
    species_hardness:
        - Continuous
        - [boost, cluster, filter]
    miniorder:
        - Continuous
        - [boost, cluster, filter, showList]
        - prefdir: -1
    brand:
        - Categorical
        - [boost, cluster, filter]    
    species:
        - Categorical
        - [boost, filter]
    finish:
        - Categorical
        - [boost, filter, show, showList]
    feature:
        - Categorical
        - [boost, filter, show, showList]
    colorrange:
        - Categorical
        - [boost, filter]
        
flooring:
    product_type: 
        - flooring_builddirect
    layout:
        - lineview
        - simple
    price:
        - Continuous
        - [boost, cluster, filter, show]
        - prefdir: -1
    width:
        - Continuous
        - [boost, cluster, filter, showList]
        - prefdir: 0
    species_hardness:
        - Continuous
        - [boost, cluster, filter]
    miniorder:
        - Continuous
        - [boost, cluster, filter, showList]
        - prefdir: -1
    brand:
        - Categorical
        - [boost, cluster, filter]    
    species:
        - Categorical
        - [boost, filter]
    finish:
        - Categorical
        - [boost, filter, show, showList]
    feature:
        - Categorical
        - [boost, filter, show, showList]
    colorrange:
        - Categorical
        - [boost, filter]
                
#############################
#     Laptops - Walmart     #
#############################
                
walmart.optemo.com:
    product_type: 
        - laptop_walmart
    layout:
        - lineview
    price:
        - Continuous
        - [boost, cluster, filter]
        - prefdir: -1
    brand:
        - Categorical
        - [boost, cluster, filter]
    hd:
        - Continuous
        - [boost, cluster, filter]
    ram:
        - Continuous
        - [boost, cluster, filter]
    screensize:
        - Continuous
        - [boost, cluster, filter]
        
laptops:
    product_type: 
        - laptop_walmart
    layout:
        - lineview
    price:
        - Continuous
        - [boost, cluster, filter]
        - prefdir: -1
    brand:
        - Categorical
        - [boost, cluster, filter]
    hd:
        - Continuous
        - [boost, cluster, filter]
    ram:
        - Continuous
        - [boost, cluster, filter]
    screensize:
        - Continuous
        - [boost, cluster, filter]