# c = continuous
# cat = categorical
# b = boolean
# boost = boostexter feature for labels

####Spaces are required between elements in an array

camera_us:
    layout:
        - gridview
    maximumresolution: 
        - Continuous
        - [boost, cluster, filter]
    displaysize:
        - Continuous
        - [boost, cluster, filter]
    price:
        - Continuous
        - [boost, cluster, filter]
    opticalzoom:
        - Continuous
        - [boost, cluster, filter]
    slr:
        - Binary
        - [boost, cluster, filter]
    brand:
        - Categorical
        - [boost, cluster, filter]
      
printer_us:
    layout:
        - gridview
    price:
        - Continuous
        - [boost, cluster, filter]
    ppm:
        - Continuous
        - [boost, cluster, filter]
    resolutionmax:
        - Continuous
        - [boost, cluster, filter]
    paperinput:
        - Continuous
        - [boost, cluster, filter]
    itemwidth:
        - Continuous
        - [boost, cluster, filter]
    printserver:
        - Binary
        - [boost, cluster, filter]
    scanner:
        - Binary
        - [boost, cluster, filter]
    brand:
        - Categorical
        - [boost, cluster, filter]
        
flooring_builddirect:
    layout:
        - lineview
    price:
        - Continuous
        - [boost, cluster, filter]
    width:
        - Continuous
        - [boost, cluster, filter]
    species_hardness:
        - Continuous
        - [boost, cluster, filter]
    miniorder:
        - Continuous
        - [boost, cluster, filter]
    brand:
        - Categorical
        - [boost, cluster, filter]    
    species:
        - Categorical
        - [filter]
    finish:
        - Categorical
        - [filter]
    feature:
        - Categorical
        - [filter]
    colorrange:
        - Categorical
        - [filter]            
            
laptop_walmart:
    layout:
        - lineview