# c = continuous
# cat = categorical
# b = boolean
# boost = boostexter feature for labels

####Spaces are required between elements in an array

camera_us:
    layout:
        - gridview
    maximumresolution: 
        - Continuous
        - [boost, cluster, filter]
    displaysize:
        - Continuous
        - [boost, cluster, filter]
    price:
        - Continuous
        - [boost, cluster, filter]
        - prefdir: -1
    opticalzoom:
        - Continuous
        - [boost, cluster, filter]
    slr:
        - Binary
        - [boost, cluster]
    brand:
        - Categorical
        - [boost, cluster, filter]
      
printer_us:
    layout:
        - gridview
    price:
        - Continuous
        - [boost, cluster, filter]
        - prefdir: -1
    ppm:
        - Continuous
        - [boost, cluster, filter]
    resolutionmax:
        - Continuous
        - [boost, cluster, filter]
    paperinput:
        - Continuous
        - [boost, cluster, filter]
    itemwidth:
        - Continuous
        - [boost, cluster, filter]
        - prefdir: -1
    printserver:
        - Binary
        - [boost, cluster, filter]
    scanner:
        - Binary
        - [boost, cluster, filter]
    brand:
        - Categorical
        - [boost, cluster, filter]
        
flooring_builddirect:
    layout:
        - lineview
    price:
        - Continuous
        - [boost, cluster, filter]
        - prefdir: -1
    width:
        - Continuous
        - [boost, cluster, filter, show]
        - prefdir: 0
    species_hardness:
        - Continuous
        - [boost, cluster]
    miniorder:
        - Continuous
        - [boost, cluster, filter, show]
        - prefdir: -1
    brand:
        - Categorical
        - [boost, cluster, filter]    
    species:
        - Categorical
        - [boost, filter]
    finish:
        - Categorical
        - [boost, filter, show]
    feature:
        - Categorical
        - [boost, filter, show]
    colorrange:
        - Categorical
        - [boost, filter]
        
laptop_walmart:
    layout:
        - lineview
    price:
        - Continuous
        - [boost, cluster, filter]
        - prefdir: -1
    brand:
        - Categorical
        - [boost, cluster, filter]
    hd:
        - Continuous
        - [boost, cluster, filter]
    ram:
        - Continuous
        - [boost, cluster, filter]
    screensize:
        - Continuous
        - [boost, cluster, filter]