####Spaces are required between elements in an array

#######################################
#    Best Buy Demo - Cameras & TVs    #
#######################################

tv_bestbuy:
    url: 
        besttv: 12
    layout: assist
    price:
        type: Continuous
        used_for: [filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    maxresolution: 
        type: Continuous
        used_for: [desc, filter, cluster, show]
    screensize:
        type: Continuous
        used_for: [desc, filter, cluster, show]
    power:
        type: Continuous
        used_for: [desc, filter, cluster, show]
    brand:
        type: Categorical
        used_for: [filter, show]
    displaytech:
        type: Categorical
        used_for: [filter, show]

#######################################
#    Cameras.BrowseThenBuy, Mobile    #
#######################################

camera_us:
    url:
        cameras: 10 # See Piwik at analytics.optemo.com for details
        cameras.browsethenbuy.com: 4
        cameras.assist.demo.optemo.com: 14
        cameras.assist: 10
    layout: assist
    maximumresolution: 
        type: Continuous
        used_for: [boost, filter, cluster, show]
    displaysize:
        type: Continuous
        used_for: [boost, filter, cluster, show]
    price:
        type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        type: Continuous
        used_for: [boost, filter, cluster, show]
    brand:
        type: Categorical
        used_for: [boost, show, filter]


camera_us:
    url: 
        cameras.direct.demo.optemo.com: 14
        cameras.direct: 10
    layout: direct
    maximumresolution: 
        type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    displaysize:
        type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    price:
        type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    brand:
        type: Categorical
        used_for: [boost, filter, show]        

camera_us:
    url:
        m.demo.optemo.com: 8
        mobile: 10
    layout: mobileview
    maximumresolution: 
        type: Continuous
        used_for: [boost, filter, cluster, show]
    displaysize:
        type: Continuous
        used_for: [boost, filter, cluster, show]
    price:
        type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        type: Continuous
        used_for: [boost, filter, cluster, show]
    brand:
        type: Categorical
        used_for: [boost, filter, show]
        
camera_bestbuy:
    url: 
        localhost: 12
        bestbuy: 12
        ilovecameras: 12
        ilovecameras.optemo.com: 12
    layout: assist
    price:
        type: Continuous
        used_for: [filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    maxresolution: 
        type: Continuous
        used_for: [desc, filter, cluster, show]
    screensize:
        type: Continuous
        used_for: [desc, filter, cluster, show]
    opticalzoom:
        type: Continuous
        used_for: [desc, filter, cluster, show]
    brand:
        type: Categorical
        used_for: [show, filter, cluster]
    color:
        type: Categorical
        used_for: [show, filter]
    customerRating:
        type: Continuous
        used_for: [filter]
    isAdvertised:
        type: Binary
        used_for: [filter]
    isClearance:
        type: Binary
        used_for: [filter]
    isOnlineOnly:
        type: Binary
        used_for: [filter]
    cmos:
        type: Binary
        used_for: [filter]
    videoresolution:
        type: categorical
        used_for: [filter]
    touchscreen:
        type: Binary
        used_for: [filter]
    oled:
        type: Binary
        used_for: [filter]
    hdmi:
        type: Binary
        used_for: [filter]
    imagestabilization:
        type: Binary
        used_for: [filter]
    waterproof:
        type: Binary
        used_for: [show, filter]

################################
#  LaserPrinterHub, Printers   #
################################

printer_us:
    url: 
        printers.browsethenbuy.com: 2
        printers.direct.demo.optemo.com: 16
        printers.direct: 10
        printers: 10
    layout: direct
    price:
        type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        type: Categorical
        used_for: [showList]
    paperinput:
        type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        type: Binary
        used_for: [boost, filter, show]
    scanner:
        type: Binary
        used_for: [boost, filter, show]
    brand:
        type: Categorical
        used_for: [boost, filter, show]
           
printer_us:
    url: 
        printers.assist.demo.optemo.com: 16
        printers.assist: 10
    layout: assist
    price:
        type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        type: Categorical
        used_for: [showList]
    paperinput:
        type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        type: Binary
        used_for: [boost, filter, show]
    scanner:
        type: Binary
        used_for: [boost, filter, show]
    brand:
        type: Categorical
        used_for: [boost, filter, show]

printer_lph:
    url: 
        laserprinterhub.com: 6
        laserprinterhub.ca: 6
        ast0.optemo.com: 6
    layout: assist
    price:
        type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        type: Categorical
        used_for: [showList]
    paperinput:
        type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        type: Binary
        used_for: [boost, filter, show]
    scanner:
        type: Binary
        used_for: [boost, filter, show]
    brand:
        type: Categorical
        used_for: [boost, filter, show]