# c = continuous
# cat = categorical
# b = boolean
# boost = boostexter feature for labels
# show = this causes display in CompareController#show
# showList = for listview, this causes display in .itemfeatures

####Spaces are required between elements in an array

#######################################
#   Cameras.BrowseThenBuy - Cameras   #
#######################################

cameras:
    product_type: camera_us
    layout: gridview
    maximumresolution: 
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    displaysize:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [boost, show, filter]

cameras.browsethenbuy.com:
    product_type: camera_us
    layout: gridview
    maximumresolution: 
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    displaysize:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]
        
cameras.direct.demo.optemo.com:
    product_type: camera_us
    layout: listview
    maximumresolution: 
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    displaysize:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]
                
cameras.assist.demo.optemo.com:
    product_type: camera_us
    layout: gridview
    maximumresolution: 
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    displaysize:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]
        
m.browsethenbuy.com:
    product_type: camera_us
    layout: mobileview
    maximumresolution: 
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    displaysize:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]

mobile:
    product_type: camera_us
    layout: mobileview
    maximumresolution: 
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    displaysize:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    opticalzoom:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]

################################
#  LaserPrinterHub - Printers  #
################################

printers.browsethenbuy.com:
    product_type: printer_us
    layout: lineview
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        feature_type: Categorical
        used_for: [showList]
    paperinput:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        feature_type: Binary
        used_for: [boost, filter, show]
    scanner:
        feature_type: Binary
        used_for: [boost, filter, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]

printers.direct.demo.optemo.com:
    product_type: printer_us
    layout: lineview
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        feature_type: Categorical
        used_for: [showList]
    paperinput:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        feature_type: Binary
        used_for: [boost, filter, show]
    scanner:
        feature_type: Binary
        used_for: [boost, filter, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]
        
printers.assist.demo.optemo.com:
    product_type: printer_us
    layout: gridview
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        feature_type: Categorical
        used_for: [showList]
    paperinput:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        feature_type: Binary
        used_for: [boost, filter, show]
    scanner:
        feature_type: Binary
        used_for: [boost, filter, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]

            
laserprinterhub.com:
    product_type: printer_lph
    layout: gridview
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        feature_type: Categorical
        used_for: [showList]
    paperinput:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        feature_type: Binary
        used_for: [boost, filter, show]
    scanner:
        feature_type: Binary
        used_for: [boost, filter, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]
    

laserprinterhub.ca:
    product_type: printer_lph
    layout: gridview
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        feature_type: Categorical
        used_for: [showList]
    paperinput:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        feature_type: Binary
        used_for: [boost, filter, show]
    scanner:
        feature_type: Binary
        used_for: [boost, filter, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]
    

localhost:
    product_type: printer_lph
    layout: gridview
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        feature_type: Categorical
        used_for: [showList]
    paperinput:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        feature_type: Binary
        used_for: [boost, filter, show]
    scanner:
        feature_type: Binary
        used_for: [boost, filter, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]
   

printers:
    product_type: printer_us
    layout: lineview
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10000
    ppm:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    resolutionmax:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    resolution:
        feature_type: Categorical
        used_for: [showList]
    paperinput:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
    itemwidth:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    printserver:
        feature_type: Binary
        used_for: [boost, filter, show]
    scanner:
        feature_type: Binary
        used_for: [boost, filter, show]
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]

#############################
#  Build Direct - Flooring  #
#############################

builddirect.optemo.com:
    product_type: flooring_builddirect
    layout: lineview
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10
    width:
        feature_type: Continuous
        used_for: [boost, filter, cluster, showList]
        prefdir: 0
    species_hardness:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    miniorder:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]    
    species:
        feature_type: Categorical
        used_for: [boost, filter, show]
    finish:
        feature_type: Categorical
        used_for: [boost, filter, show, showList]
    feature:
        feature_type: Categorical
        used_for: [boost, filter, show, showList]
    colorrange:
        feature_type: Categorical
        used_for: [boost, filter, show]
        
flooring:
    product_type: flooring_builddirect
    layout: lineview
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 1
        max: 10
    width:
        feature_type: Continuous
        used_for: [boost, filter, cluster, showList]
        prefdir: 0
    species_hardness:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    miniorder:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show, showList]
        prefdir: -1
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]    
    species:
        feature_type: Categorical
        used_for: [boost, filter, show]
    finish:
        feature_type: Categorical
        used_for: [boost, filter, show, showList]
    feature:
        feature_type: Categorical
        used_for: [boost, filter, show, showList]
    colorrange:
        feature_type: Categorical
        used_for: [boost, filter, show]
#############################
#     Laptops - Walmart     #
#############################
                
walmart.optemo.com:
    product_type: laptop_walmart
    layout: lineview
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 10
        max: 2000
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]
    hd:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    ram:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    screensize:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        
laptops:
    product_type: laptop_walmart
    layout: lineview
    price:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
        prefdir: -1
        min: 10
        max: 2000
    brand:
        feature_type: Categorical
        used_for: [boost, filter, show]
    hd:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    ram:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
    screensize:
        feature_type: Continuous
        used_for: [boost, filter, cluster, show]
