production:
  solr:
    hostname: electra
    port: 8983
    log_level: WARNING

development:
  solr:
    hostname: electra
    port: 8983
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING