# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20120417191944) do

  create_table "accessories", :force => true do |t|
    t.integer  "product_id"
    t.integer  "count"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "name"
    t.string   "value"
    t.string   "acc_type"
  end

  create_table "all_daily_specs", :id => false, :force => true do |t|
    t.integer  "id",           :default => 0, :null => false
    t.string   "sku"
    t.string   "name"
    t.string   "spec_type"
    t.string   "value_txt"
    t.float    "value_flt"
    t.boolean  "value_bin"
    t.string   "product_type"
    t.date     "date"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "amazon_alls", :force => true do |t|
    t.text     "title"
    t.string   "imagesurl"
    t.integer  "imagesheight"
    t.integer  "imageswidth"
    t.string   "imagemurl"
    t.integer  "imagemheight"
    t.integer  "imagemwidth"
    t.string   "imagelurl"
    t.integer  "imagelheight"
    t.integer  "imagelwidth"
    t.integer  "price"
    t.string   "pricestr"
    t.boolean  "instock"
    t.integer  "bestoffer",                       :limit => 1
    t.string   "pricehistory"
    t.integer  "price_ca"
    t.string   "price_ca_str"
    t.boolean  "instock_ca"
    t.boolean  "bestoffer_ca"
    t.boolean  "iseligibleforsupersavershipping"
    t.float    "averagereviewrating"
    t.integer  "totalreviews"
    t.datetime "created_at",                                                          :null => false
    t.datetime "updated_at",                                                          :null => false
    t.string   "asin"
    t.text     "detailpageurl"
    t.string   "binding"
    t.string   "brand"
    t.string   "color"
    t.string   "cpumanufacturer"
    t.float    "cpuspeed"
    t.string   "cputype"
    t.float    "displaysize"
    t.string   "ean"
    t.text     "feature"
    t.string   "graphicsmemorysize"
    t.boolean  "isautographed"
    t.boolean  "ismemorabilia"
    t.integer  "itemheight"
    t.integer  "itemlength"
    t.integer  "itemwidth"
    t.integer  "itemweight"
    t.string   "label"
    t.string   "language"
    t.string   "legaldisclaimer"
    t.string   "listpricestr"
    t.integer  "listpriceint"
    t.string   "manufacturer"
    t.string   "model"
    t.string   "modemdescription"
    t.string   "mpn"
    t.string   "nativeresolution"
    t.integer  "numberofitems"
    t.integer  "packageheight"
    t.integer  "packagelength"
    t.integer  "packagewidth"
    t.integer  "packageweight"
    t.integer  "processorcount"
    t.string   "productgroup"
    t.string   "publisher"
    t.text     "specialfeatures"
    t.string   "studio"
    t.integer  "systemmemorysize"
    t.string   "systemmemorytype"
    t.string   "warranty"
    t.float    "ppm"
    t.float    "ttp"
    t.string   "resolution"
    t.string   "duplex"
    t.string   "connectivity"
    t.string   "papersize"
    t.integer  "paperoutput"
    t.string   "dimensions"
    t.integer  "dutycycle"
    t.integer  "paperinput"
    t.string   "special"
    t.float    "ppmcolor"
    t.string   "platform"
    t.boolean  "colorprinter"
    t.boolean  "scanner"
    t.datetime "scrapedat"
    t.boolean  "nodetails"
    t.boolean  "printserver"
    t.integer  "resolutionmax"
    t.boolean  "fax"
    t.boolean  "bw"
    t.integer  "resolutionarea"
    t.integer  "product_id"
    t.string   "product_type",                                 :default => "Printer"
  end

  create_table "amazon_groups", :force => true do |t|
    t.datetime "created_at",                            :null => false
    t.datetime "updated_at",                            :null => false
    t.boolean  "processed",          :default => false
    t.string   "url"
    t.string   "brand"
    t.string   "megapixels_range"
    t.string   "opticalZoom_range"
    t.string   "displaySize_range"
    t.string   "imageStabilization"
    t.string   "viewfinderType"
    t.boolean  "leaf",               :default => false
    t.datetime "scrapedAt"
  end

  create_table "amazon_printers", :force => true do |t|
    t.text     "title"
    t.string   "imagesurl"
    t.integer  "imagesheight"
    t.integer  "imageswidth"
    t.string   "imagemurl"
    t.integer  "imagemheight"
    t.integer  "imagemwidth"
    t.string   "imagelurl"
    t.integer  "imagelheight"
    t.integer  "imagelwidth"
    t.integer  "price"
    t.string   "pricestr"
    t.boolean  "instock"
    t.integer  "bestoffer",                       :limit => 1
    t.string   "pricehistory"
    t.integer  "price_ca"
    t.string   "price_ca_str"
    t.boolean  "instock_ca"
    t.boolean  "bestoffer_ca"
    t.boolean  "iseligibleforsupersavershipping"
    t.float    "averagereviewrating"
    t.integer  "totalreviews"
    t.datetime "created_at",                                                          :null => false
    t.datetime "updated_at",                                                          :null => false
    t.string   "asin"
    t.text     "detailpageurl"
    t.string   "binding"
    t.string   "brand"
    t.string   "color"
    t.string   "cpumanufacturer"
    t.float    "cpuspeed"
    t.string   "cputype"
    t.float    "displaysize"
    t.string   "ean"
    t.text     "feature"
    t.string   "graphicsmemorysize"
    t.boolean  "isautographed"
    t.boolean  "ismemorabilia"
    t.integer  "itemheight"
    t.integer  "itemlength"
    t.integer  "itemwidth"
    t.integer  "itemweight"
    t.string   "label"
    t.string   "language"
    t.string   "legaldisclaimer"
    t.string   "listpricestr"
    t.integer  "listpriceint"
    t.string   "manufacturer"
    t.string   "model"
    t.string   "modemdescription"
    t.string   "mpn"
    t.string   "nativeresolution"
    t.integer  "numberofitems"
    t.integer  "packageheight"
    t.integer  "packagelength"
    t.integer  "packagewidth"
    t.integer  "packageweight"
    t.integer  "processorcount"
    t.string   "productgroup"
    t.string   "publisher"
    t.text     "specialfeatures"
    t.string   "studio"
    t.integer  "systemmemorysize"
    t.string   "systemmemorytype"
    t.string   "warranty"
    t.float    "ppm"
    t.float    "ttp"
    t.string   "resolution"
    t.string   "duplex"
    t.string   "connectivity"
    t.string   "papersize"
    t.integer  "paperoutput"
    t.string   "dimensions"
    t.integer  "dutycycle"
    t.integer  "paperinput"
    t.string   "special"
    t.float    "ppmcolor"
    t.string   "platform"
    t.boolean  "colorprinter"
    t.boolean  "scanner"
    t.datetime "scrapedat"
    t.boolean  "nodetails"
    t.boolean  "printserver"
    t.integer  "resolutionmax"
    t.boolean  "fax"
    t.boolean  "bw"
    t.integer  "resolutionarea"
    t.integer  "product_id"
    t.string   "product_type",                                 :default => "Printer"
  end

  create_table "best_buy_offerings", :force => true do |t|
    t.integer  "retailer_offering_id"
    t.string   "bb_class"
    t.integer  "classId"
    t.string   "subclass"
    t.integer  "subclassId"
    t.integer  "productId"
    t.string   "department"
    t.integer  "departmentId"
    t.string   "type"
    t.string   "categoryPath"
    t.string   "addToCartUrl"
    t.string   "affiliateUrl"
    t.string   "affiliateAddToCartUrl"
    t.string   "mobileUrl"
    t.string   "url"
    t.string   "cjAffiliateUrl"
    t.string   "cjAffiliateAddToCartUrl"
    t.string   "sku"
    t.string   "warrantyParts"
    t.string   "warrantyLabor"
    t.boolean  "bb_new"
    t.boolean  "nationalFeatured"
    t.boolean  "navigability"
    t.datetime "releaseDate"
    t.datetime "startDate"
    t.datetime "itemUpdateDate"
    t.datetime "created_at",              :null => false
    t.datetime "updated_at",              :null => false
  end

  create_table "best_buy_phones", :force => true do |t|
    t.string   "title"
    t.string   "description"
    t.string   "link"
    t.string   "category"
    t.string   "guid"
    t.string   "CategoryID"
    t.string   "Manufacturer"
    t.string   "ProvinceCode"
    t.string   "ImageUrl"
    t.string   "LongDescription"
    t.string   "CatGroup"
    t.string   "CatDept"
    t.string   "CatClass"
    t.string   "CatSubClass"
    t.string   "Price"
    t.string   "BacklitKeypad"
    t.string   "BatteryType"
    t.string   "CPUSpeed"
    t.string   "Calculator"
    t.string   "Calendar"
    t.string   "Carrier"
    t.string   "ChangeableFaceplateCapable"
    t.string   "ConnectionPort"
    t.string   "CustomizableRingTones"
    t.string   "DataCapabilities"
    t.string   "DisplayType"
    t.string   "ExpansionSlots"
    t.string   "Extras"
    t.string   "FlashUpgradeable"
    t.string   "Games"
    t.string   "HandsfreeSpeakerphone"
    t.string   "IncludedInBox"
    t.string   "KeyboardType"
    t.string   "KeypadLock"
    t.string   "MP3Capable"
    t.string   "MemorySize"
    t.string   "MfrPartNumber"
    t.string   "ModemType"
    t.string   "NumberofDisplayLines"
    t.string   "NumberofModes"
    t.string   "OperatingSystem"
    t.string   "OperatingSystemCompatibility"
    t.string   "OrderConditions"
    t.string   "PhoneBookCapacity"
    t.string   "ProductDimensions"
    t.string   "ProductWarranty"
    t.string   "ProductWeight"
    t.string   "ROMSize"
    t.string   "Resolution"
    t.string   "Spreadsheet"
    t.string   "StandbyTime"
    t.string   "StylusEntry"
    t.string   "SupportsCallerID"
    t.string   "TalkTime"
    t.string   "VibrateMode"
    t.string   "VoiceRecording"
    t.string   "WebBrowser"
    t.string   "WebCode"
    t.string   "WordProcessor"
    t.datetime "created_at",                   :null => false
    t.datetime "updated_at",                   :null => false
  end

  create_table "best_buy_printers", :force => true do |t|
    t.string   "bb_class"
    t.integer  "classId"
    t.string   "subclass"
    t.integer  "subclassId"
    t.integer  "productId"
    t.string   "department"
    t.integer  "departmentId"
    t.string   "type"
    t.string   "categoryPath"
    t.string   "addToCartUrl"
    t.string   "affiliateUrl"
    t.string   "affiliateAddToCartUrl"
    t.string   "mobileUrl"
    t.string   "url"
    t.string   "cjAffiliateUrl"
    t.string   "cjAffiliateAddToCartUrl"
    t.string   "sku"
    t.string   "warrantyParts"
    t.string   "warrantyLabor"
    t.boolean  "bb_new"
    t.boolean  "nationalFeatured"
    t.boolean  "navigability"
    t.datetime "releaseDate"
    t.datetime "startDate"
    t.datetime "itemUpdateDate"
    t.string   "source"
    t.boolean  "active"
    t.string   "activeUpdateDate"
    t.boolean  "printOnly"
    t.boolean  "inStoreAvailability"
    t.string   "inStoreAvailabilityText"
    t.datetime "inStoreAvailabilityUpdateDate"
    t.boolean  "onlineAvailability"
    t.string   "onlineAvailabilityText"
    t.datetime "onlineAvailabilityUpdateDate"
    t.float    "regularPrice"
    t.float    "salePrice"
    t.datetime "priceUpdateDate"
    t.string   "dollarSavings"
    t.float    "shippingCost"
    t.boolean  "freeShipping"
    t.string   "specialOrder"
    t.string   "orderable"
    t.string   "accessoriesImage"
    t.string   "angleImage"
    t.string   "remoteControlImage"
    t.string   "alternateViewsImage"
    t.string   "leftViewImage"
    t.string   "rightViewImage"
    t.string   "backViewImage"
    t.string   "topViewImage"
    t.string   "largeFrontImage"
    t.string   "thumbnailImage"
    t.string   "image"
    t.string   "mediumImage"
    t.string   "largeImage"
    t.string   "energyGuideImage"
    t.string   "name"
    t.string   "upc"
    t.string   "color"
    t.string   "modelNumber"
    t.string   "description"
    t.string   "shortDescription"
    t.text     "longDescription"
    t.string   "manufacturer"
    t.string   "weight"
    t.float    "width"
    t.float    "height"
    t.float    "depth"
    t.float    "shippingWeight"
    t.string   "format"
    t.integer  "customerReviewCount"
    t.float    "customerReviewAverage"
    t.integer  "printer_id"
    t.datetime "created_at",                    :null => false
    t.datetime "updated_at",                    :null => false
  end

  create_table "best_buy_products", :force => true do |t|
    t.integer  "product_id"
    t.string   "product_type"
    t.string   "accessoriesImage"
    t.string   "angleImage"
    t.string   "remoteControlImage"
    t.string   "alternateViewsImage"
    t.string   "leftViewImage"
    t.string   "rightViewImage"
    t.string   "backViewImage"
    t.string   "topViewImage"
    t.string   "largeFrontImage"
    t.string   "thumbnailImage"
    t.string   "image"
    t.string   "mediumImage"
    t.string   "largeImage"
    t.string   "energyGuideImage"
    t.string   "name"
    t.string   "upc"
    t.string   "modelNumber"
    t.string   "description"
    t.string   "shortDescription"
    t.text     "longDescription"
    t.string   "manufacturer"
    t.string   "weight"
    t.float    "width"
    t.float    "height"
    t.float    "depth"
    t.float    "shippingWeight"
    t.integer  "customerReviewCount"
    t.float    "customerReviewAverage"
    t.datetime "created_at",            :null => false
    t.datetime "updated_at",            :null => false
  end

  create_table "bin_specs", :force => true do |t|
    t.integer  "product_id"
    t.string   "name"
    t.boolean  "value"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean  "modified"
  end

  add_index "bin_specs", ["name"], :name => "index_bin_specs_on_name"
  add_index "bin_specs", ["product_id"], :name => "index_bin_specs_on_product_id"

  create_table "cameras", :force => true do |t|
    t.datetime "created_at",          :null => false
    t.datetime "updated_at",          :null => false
    t.text     "title"
    t.string   "imagesurl"
    t.integer  "imagesheight"
    t.integer  "imageswidth"
    t.string   "imagemurl"
    t.integer  "imagemheight"
    t.integer  "imagemwidth"
    t.string   "imagelurl"
    t.integer  "imagelheight"
    t.integer  "imagelwidth"
    t.text     "detailpageurl"
    t.text     "manufacturerurl"
    t.string   "brand"
    t.string   "model"
    t.string   "mpn"
    t.string   "dimensions"
    t.integer  "itemwidth"
    t.integer  "itemlength"
    t.integer  "itemheight"
    t.integer  "itemweight"
    t.integer  "packageheight"
    t.integer  "packagelength"
    t.integer  "packagewidth"
    t.integer  "packageweight"
    t.float    "opticalzoom"
    t.float    "maximumresolution"
    t.string   "resolution"
    t.float    "displaysize"
    t.boolean  "slr"
    t.boolean  "waterproof"
    t.float    "maximumfocallength"
    t.float    "minimumfocallength"
    t.float    "digitalzoom"
    t.boolean  "batteriesincluded"
    t.string   "batterydescription"
    t.string   "connectivity"
    t.boolean  "hasredeyereduction"
    t.string   "includedsoftware"
    t.float    "averagereviewrating"
    t.integer  "totalreviews"
    t.text     "reviewtext"
    t.integer  "price"
    t.string   "pricestr"
    t.boolean  "instock"
    t.boolean  "bestoffer"
    t.string   "pricehistory"
    t.integer  "price_ca"
    t.string   "price_ca_str"
    t.boolean  "instock_ca"
    t.boolean  "bestoffer_ca"
  end

  add_index "cameras", ["instock"], :name => "index_cameras_on_instock"
  add_index "cameras", ["instock_ca"], :name => "index_cameras_on_instock_ca"

  create_table "cat_specs", :force => true do |t|
    t.integer  "product_id"
    t.string   "name"
    t.string   "value"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean  "modified"
  end

  add_index "cat_specs", ["name"], :name => "index_cat_specs_on_name"
  add_index "cat_specs", ["product_id"], :name => "index_cat_specs_on_product_id"

  create_table "cont_specs", :force => true do |t|
    t.integer  "product_id"
    t.string   "name"
    t.float    "value"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean  "modified"
  end

  add_index "cont_specs", ["name", "product_id"], :name => "index_cont_specs_on_name_and_product_id"
  add_index "cont_specs", ["product_id"], :name => "index_cont_specs_on_product_id"
  add_index "cont_specs", ["value"], :name => "index_cont_specs_on_value"

  create_table "daily_specs", :force => true do |t|
    t.string   "sku"
    t.string   "name"
    t.string   "spec_type"
    t.string   "value_txt"
    t.float    "value_flt"
    t.boolean  "value_bin"
    t.string   "product_type"
    t.date     "date"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "daily_specs", ["sku", "name", "product_type", "date"], :name => "sku", :unique => true

  create_table "dynamic_facets", :force => true do |t|
    t.integer "facet_id", :null => false
    t.string  "category", :null => false
  end

  add_index "dynamic_facets", ["facet_id", "category"], :name => "index_dynamic_facets_on_facet_id_and_category", :unique => true

  create_table "equivalences", :force => true do |t|
    t.integer "product_id"
    t.integer "eq_id"
  end

  add_index "equivalences", ["eq_id"], :name => "index_equivalences_on_eq_id"
  add_index "equivalences", ["product_id"], :name => "index_equivalences_on_product_id"

  create_table "facets", :force => true do |t|
    t.string  "name",                                    :null => false
    t.string  "feature_type", :default => "Categorical", :null => false
    t.string  "used_for",     :default => "show"
    t.float   "value"
    t.string  "style",        :default => ""
    t.boolean "active",       :default => true
    t.string  "product_type"
    t.string  "ui"
  end

  create_table "factors", :force => true do |t|
    t.datetime "created_at",   :null => false
    t.datetime "updated_at",   :null => false
    t.string   "product_type"
    t.integer  "product_id"
    t.string   "cont_var"
    t.float    "value"
  end

  create_table "keyword_searches", :force => true do |t|
    t.string  "keyword"
    t.integer "product_id"
  end

  add_index "keyword_searches", ["keyword"], :name => "index_keyword_searches_on_keyword"
  add_index "keyword_searches", ["product_id"], :name => "index_keyword_searches_on_product_id"

  create_table "newegg_offerings", :force => true do |t|
    t.datetime "created_at",         :null => false
    t.datetime "updated_at",         :null => false
    t.integer  "printer_id"
    t.string   "item_number"
    t.integer  "product_id"
    t.string   "product_type"
    t.integer  "offering_id"
    t.integer  "retailer_id"
    t.integer  "priceint"
    t.string   "pricestr"
    t.string   "region"
    t.boolean  "instock"
    t.boolean  "toolow"
    t.datetime "priceUpdate"
    t.string   "availability"
    t.datetime "availabilityUpdate"
    t.text     "url"
    t.boolean  "active"
    t.datetime "activeUpdate"
    t.boolean  "freeShipping"
  end

  create_table "newegg_printer_scraped_datas", :force => true do |t|
    t.datetime "created_at",             :null => false
    t.datetime "updated_at",             :null => false
    t.string   "item_number"
    t.string   "manufacturer"
    t.string   "series"
    t.string   "brand"
    t.boolean  "toolow"
    t.float    "saleprice"
    t.float    "listprice"
    t.string   "imageurl"
    t.boolean  "recertified"
    t.boolean  "openbox"
    t.string   "shipping"
    t.string   "title"
    t.string   "manufacturerproducturl"
    t.string   "stock"
    t.string   "model"
    t.string   "recommendeduse"
    t.string   "dimensions"
    t.integer  "weight"
    t.string   "outputtype"
    t.string   "lasertechnology"
    t.float    "blackprintspeed"
    t.float    "colorprintspeed"
    t.float    "timetofirstpageseconds"
    t.string   "blackprintquality"
    t.string   "colorprintquality"
    t.string   "printlanguagesstd"
    t.string   "duplexprinting"
    t.integer  "maxdutycycle"
    t.string   "papertraysstd"
    t.string   "papertraysmax"
    t.integer  "inputcapacitystd"
    t.integer  "inputcapacitymax"
    t.integer  "outputcapacitystd"
    t.integer  "outputcapacitymax"
    t.string   "mediatype"
    t.string   "mediasizessupported"
    t.string   "usbports"
    t.string   "lptports"
    t.string   "networkports"
    t.string   "otherports"
    t.string   "microprocessortype"
    t.string   "processormhz"
    t.string   "memorystd"
    t.string   "memorymax"
    t.string   "cartridgescompatible"
    t.string   "powerrequirements"
    t.string   "powerconsumption"
    t.string   "windowscompatible"
    t.string   "macintoshcompatible"
    t.string   "parts"
    t.string   "labor"
    t.string   "copyqualityblack"
    t.string   "scanresolutionenhanced"
    t.string   "windowsvista"
    t.string   "other"
    t.string   "faxfeatures"
    t.string   "noiselevelapprox"
    t.string   "modemspeed"
    t.string   "emulations"
    t.string   "comports"
    t.string   "display"
    t.string   "copyspeedblack"
    t.string   "maxdocumentenlargement"
    t.string   "maxdocumentreduction"
    t.string   "maxnumberofcopies"
    t.string   "scancolordepth"
    t.string   "scanresolutionoptical"
    t.string   "packagecontents"
    t.string   "faxmemory"
    t.string   "copyspeedcolor"
    t.string   "faxtransmissionspeed"
    t.string   "scanelement"
    t.string   "faxresolutions"
    t.string   "softwareincluded"
    t.string   "connectivitytechnology"
    t.string   "colorfax"
    t.string   "copyqualitycolor"
    t.string   "borderlessphotosizes"
    t.string   "scanresolutionhardware"
  end

  create_table "newegg_printers", :force => true do |t|
    t.string   "item_number"
    t.integer  "product_id"
    t.string   "product_type"
    t.string   "model"
    t.string   "mpn"
    t.string   "series"
    t.string   "brand"
    t.integer  "listpriceint"
    t.string   "listpricestr"
    t.string   "imageurl"
    t.text     "detailpageurl"
    t.string   "recommendeduse"
    t.string   "dimensions"
    t.integer  "itemheight"
    t.integer  "itemwidth"
    t.integer  "itemlength"
    t.integer  "itemweight"
    t.boolean  "colorprinter"
    t.boolean  "printserver"
    t.boolean  "scanner"
    t.datetime "scrapedat"
    t.string   "lasertechnology"
    t.string   "platform"
    t.string   "warranty"
    t.float    "ppm"
    t.float    "ppmcolor"
    t.float    "ttp"
    t.string   "resolution"
    t.string   "language"
    t.string   "duplex"
    t.integer  "dutycycle"
    t.integer  "paperinput"
    t.integer  "paperinputmax"
    t.integer  "paperoutput"
    t.integer  "paperoutputmax"
    t.string   "systemmemory"
    t.string   "systemmemorymax"
    t.string   "mediatype"
    t.string   "papersize"
    t.string   "cputype"
    t.float    "cpuspeed"
    t.string   "connectivity"
    t.string   "special"
    t.string   "usbports"
    t.string   "lptports"
    t.string   "networkports"
    t.string   "otherports"
    t.string   "comports"
    t.string   "copyspeedblack"
    t.string   "copyspeedcolor"
    t.string   "copyqualityblack"
    t.string   "copyqualitycolor"
    t.string   "maxnumberofcopies"
    t.string   "scanresolutionenhanced"
    t.string   "maxdocumentenlargement"
    t.string   "maxdocumentreduction"
    t.string   "scancolordepth"
    t.string   "scanresolutionoptical"
    t.string   "scanresolutionhardware"
    t.string   "scanelement"
    t.string   "faxfeatures"
    t.string   "faxmemory"
    t.string   "faxtransmissionspeed"
    t.string   "colorfax"
    t.string   "faxresolutions"
    t.string   "noiselevelapprox"
    t.string   "modemspeed"
    t.string   "emulations"
    t.string   "display"
    t.string   "packagecontents"
    t.string   "softwareincluded"
    t.string   "borderlessphotosizes"
    t.string   "colorresolution"
    t.string   "papertraysstd"
    t.string   "papertraysmax"
    t.string   "cartridgescompatible"
    t.string   "powerrequirements"
    t.string   "powerconsumption"
    t.integer  "resolutionmax"
    t.string   "title"
    t.string   "region"
  end

  create_table "preference_relations", :force => true do |t|
    t.datetime "created_at", :null => false
    t.datetime "updated_at", :null => false
    t.integer  "session_id"
    t.integer  "lower"
    t.integer  "higher"
    t.float    "weight"
  end

  create_table "printers", :force => true do |t|
    t.text     "title"
    t.string   "imagesurl"
    t.integer  "imagesheight"
    t.integer  "imageswidth"
    t.string   "imagemurl"
    t.integer  "imagemheight"
    t.integer  "imagemwidth"
    t.string   "imagelurl"
    t.integer  "imagelheight"
    t.integer  "imagelwidth"
    t.integer  "price"
    t.string   "pricestr"
    t.boolean  "instock"
    t.integer  "bestoffer",                       :limit => 1
    t.string   "pricehistory"
    t.integer  "price_ca"
    t.string   "price_ca_str"
    t.boolean  "instock_ca"
    t.boolean  "bestoffer_ca"
    t.boolean  "iseligibleforsupersavershipping"
    t.float    "averagereviewrating"
    t.integer  "totalreviews"
    t.datetime "created_at",                                   :null => false
    t.datetime "updated_at",                                   :null => false
    t.string   "dimensions"
    t.integer  "itemwidth"
    t.integer  "itemlength"
    t.integer  "itemheight"
    t.integer  "itemweight"
    t.integer  "packageheight"
    t.integer  "packagelength"
    t.integer  "packagewidth"
    t.integer  "packageweight"
    t.string   "brand"
    t.string   "model"
    t.string   "mpn"
    t.float    "ppm"
    t.string   "resolution"
    t.integer  "resolutionmax"
    t.integer  "paperinput"
    t.boolean  "scanner"
    t.boolean  "printserver"
    t.float    "displaysize"
    t.float    "ttp"
    t.string   "duplex"
    t.boolean  "colorprinter"
    t.boolean  "fax"
    t.string   "papersize"
    t.integer  "paperoutput"
    t.string   "connectivity"
    t.integer  "dutycycle"
    t.string   "special"
    t.float    "ppmcolor"
    t.string   "platform"
    t.string   "ean"
    t.text     "feature"
    t.integer  "listpriceint"
    t.string   "warranty"
    t.datetime "scrapedat"
    t.boolean  "nodetails"
    t.boolean  "bw"
    t.string   "manufacturerproducturl"
  end

  create_table "product_bundles", :force => true do |t|
    t.integer  "bundle_id"
    t.integer  "product_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "product_bundles", ["bundle_id"], :name => "index_product_bundles_on_bundle_id", :unique => true

  create_table "product_categories", :force => true do |t|
    t.string  "product_type"
    t.string  "feed_id"
    t.string  "retailer"
    t.integer "l_id"
    t.integer "r_id"
    t.integer "level"
  end

  create_table "product_siblings", :force => true do |t|
    t.integer  "product_id"
    t.integer  "sibling_id"
    t.string   "name"
    t.string   "value"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "product_siblings", ["product_id"], :name => "index_product_siblings_on_product_id"

  create_table "products", :force => true do |t|
    t.string  "sku"
    t.boolean "instock"
    t.string  "retailer"
  end

  create_table "referrals", :force => true do |t|
    t.integer  "product_id"
    t.string   "product_type"
    t.integer  "session_id"
    t.integer  "retailer_offering_id"
    t.datetime "created_at",           :null => false
    t.datetime "updated_at",           :null => false
  end

  create_table "results_scraping_rules", :id => false, :force => true do |t|
    t.integer "result_id"
    t.integer "scraping_rule_id"
  end

  create_table "retailer_offerings", :force => true do |t|
    t.integer  "product_id"
    t.string   "product_type"
    t.string   "pricehistory"
    t.string   "region"
    t.string   "merchant"
    t.integer  "priceint"
    t.string   "pricestr"
    t.datetime "priceUpdate"
    t.integer  "shippingCost"
    t.integer  "tax"
    t.string   "state"
    t.boolean  "stock"
    t.boolean  "toolow"
    t.string   "availability"
    t.datetime "availabilityUpdate"
    t.boolean  "iseligibleforsupersavershipping"
    t.text     "url"
    t.boolean  "active"
    t.datetime "activeUpdate"
    t.boolean  "freeShipping"
    t.datetime "created_at",                      :null => false
    t.datetime "updated_at",                      :null => false
    t.integer  "retailer_id"
    t.string   "local_id"
  end

  create_table "retailers", :force => true do |t|
    t.string   "url"
    t.string   "name"
    t.string   "image"
    t.string   "local_id_name"
    t.datetime "created_at",    :null => false
    t.datetime "updated_at",    :null => false
  end

  create_table "reviews", :force => true do |t|
    t.string   "product_type"
    t.integer  "product_id"
    t.integer  "rating"
    t.integer  "helpfulvotes"
    t.datetime "date"
    t.string   "customerid"
    t.integer  "totalvotes"
    t.text     "content"
    t.string   "local_id"
    t.string   "source"
    t.string   "summary"
    t.datetime "created_at",   :null => false
    t.datetime "updated_at",   :null => false
  end

  create_table "scraping_corrections", :force => true do |t|
    t.string   "product_id"
    t.string   "raw"
    t.text     "corrected"
    t.integer  "scraping_rule_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "scraping_corrections", ["product_id"], :name => "index_scraping_corrections_on_product_id"

  create_table "scraping_rules", :force => true do |t|
    t.string  "local_featurename"
    t.string  "remote_featurename"
    t.text    "regex"
    t.string  "product_type"
    t.float   "min"
    t.float   "max"
    t.text    "valid_inputs"
    t.string  "rule_type"
    t.integer "priority",           :default => 0
    t.boolean "french",             :default => false
    t.boolean "bilingual",          :default => false
  end

  create_table "searches", :force => true do |t|
    t.integer  "parent_id"
    t.boolean  "initial"
    t.string   "keyword_search"
    t.integer  "page"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "sortby"
    t.string   "product_type"
  end

  create_table "sessions", :force => true do |t|
    t.datetime "created_at",   :null => false
    t.datetime "updated_at",   :null => false
    t.string   "user"
    t.string   "ip"
    t.integer  "parent_id"
    t.string   "product_type"
    t.boolean  "filter"
    t.string   "searchterm"
    t.text     "searchpids"
  end

  create_table "text_specs", :force => true do |t|
    t.integer  "product_id"
    t.string   "name"
    t.text     "value"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean  "modified"
  end

  add_index "text_specs", ["product_id", "name"], :name => "index_text_specs_on_product_id_and_name"

  create_table "tiger_printers", :force => true do |t|
    t.datetime "created_at",      :null => false
    t.datetime "updated_at",      :null => false
    t.text     "title"
    t.string   "brand"
    t.string   "model"
    t.text     "tigerurl"
    t.string   "mpn"
    t.string   "upcno"
    t.integer  "price"
    t.string   "pricestr"
    t.integer  "listpriceint"
    t.string   "listpricestr"
    t.integer  "bestoffer"
    t.boolean  "instock"
    t.integer  "price_ca"
    t.string   "pricestr_ca"
    t.integer  "listpriceint_ca"
    t.string   "listpricestr_ca"
    t.boolean  "instock_ca"
    t.float    "ppm"
    t.integer  "paperinput"
    t.integer  "resolutionmax"
    t.integer  "itemheight"
    t.integer  "itemlength"
    t.integer  "itemwidth"
    t.boolean  "scanner"
    t.boolean  "printserver"
    t.integer  "itemweight"
    t.integer  "packageheight"
    t.integer  "packagelength"
    t.integer  "packagewidth"
    t.integer  "packageweight"
    t.string   "warranty"
    t.float    "ttp"
    t.string   "resolution"
    t.string   "duplex"
    t.string   "connectivity"
    t.string   "papersize"
    t.integer  "paperoutput"
    t.string   "dimensions"
    t.integer  "dutycycle"
    t.float    "ppmcolor"
    t.string   "platform"
    t.boolean  "colorprinter"
    t.datetime "scrapedat"
  end

  create_table "tiger_scrapeds", :force => true do |t|
    t.datetime "created_at",           :null => false
    t.datetime "updated_at",           :null => false
    t.string   "tigerurl"
    t.text     "title"
    t.string   "itemnumber"
    t.string   "model"
    t.string   "region"
    t.string   "manufacturedby"
    t.string   "warrantyprovidedby"
    t.string   "shippingweight"
    t.string   "mfgpartno"
    t.string   "upcno"
    t.string   "boxsize"
    t.string   "availability"
    t.string   "itmdets"
    t.string   "finalprice"
    t.string   "instantsavings"
    t.string   "originalprice"
    t.string   "price"
    t.string   "allinone"
    t.string   "approximatepageyield"
    t.string   "automaticfeeder"
    t.string   "color"
    t.string   "coloroutput"
    t.string   "condition"
    t.string   "connectivity"
    t.string   "dimensions"
    t.string   "duplexprinting"
    t.string   "faxcapability"
    t.string   "firstpageoutputtime"
    t.string   "maximumdutycycle"
    t.string   "memoryincluded"
    t.string   "networkready"
    t.string   "optionalconnectivity"
    t.string   "optionalpaperinput"
    t.string   "papersizessupported"
    t.string   "powersource"
    t.string   "powersupply"
    t.string   "printeruse"
    t.string   "printmethod"
    t.string   "printspeed"
    t.string   "printspeedbw"
    t.string   "printspeedcolor"
    t.string   "printtechnology"
    t.string   "processor"
    t.string   "producttype"
    t.string   "protocols"
    t.string   "quantity"
    t.string   "resolution"
    t.string   "specialfeatures"
    t.string   "standardpaperinput"
    t.string   "standardpaperoutput"
    t.string   "transferrate"
    t.string   "wireless"
  end

  create_table "translations", :force => true do |t|
    t.string   "locale"
    t.string   "key"
    t.text     "value"
    t.text     "interpolations"
    t.boolean  "is_proc",        :default => false
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "userdatabins", :force => true do |t|
    t.integer  "search_id"
    t.string   "name"
    t.boolean  "value"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "userdatacats", :force => true do |t|
    t.integer  "search_id"
    t.string   "name"
    t.string   "value"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "userdataconts", :force => true do |t|
    t.integer  "search_id"
    t.string   "name"
    t.float    "min"
    t.float    "max"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "users", :force => true do |t|
    t.datetime "created_at"
  end

  create_table "welcomes", :force => true do |t|
    t.string   "email"
    t.datetime "created_at", :null => false
    t.datetime "updated_at", :null => false
  end

end
