# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20101019233312) do

  create_table "amazon_alls", :force => true do |t|
    t.text     "title"
    t.integer  "price"
    t.string   "pricestr"
    t.boolean  "iseligibleforsupersavershipping"
    t.integer  "bestoffer"
    t.string   "pricehistory"
    t.string   "imagesurl"
    t.integer  "imagesheight"
    t.integer  "imageswidth"
    t.string   "imagemurl"
    t.integer  "imagemheight"
    t.integer  "imagemwidth"
    t.string   "imagelurl"
    t.integer  "imagelheight"
    t.integer  "imagelwidth"
    t.boolean  "instock"
    t.float    "averagereviewrating"
    t.integer  "totalreviews"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "asin"
    t.text     "detailpageurl"
    t.string   "binding"
    t.string   "brand"
    t.string   "color"
    t.string   "cpumanufacturer"
    t.float    "cpuspeed"
    t.string   "cputype"
    t.float    "displaysize"
    t.string   "ean"
    t.text     "feature"
    t.string   "graphicsmemorysize"
    t.boolean  "isautographed"
    t.boolean  "ismemorabilia"
    t.integer  "itemheight"
    t.integer  "itemlength"
    t.integer  "itemwidth"
    t.integer  "itemweight"
    t.string   "label"
    t.string   "language"
    t.string   "legaldisclaimer"
    t.string   "listpricestr"
    t.integer  "listpriceint"
    t.string   "manufacturer"
    t.string   "model"
    t.string   "modemdescription"
    t.string   "mpn"
    t.string   "nativeresolution"
    t.integer  "numberofitems"
    t.integer  "packageheight"
    t.integer  "packagelength"
    t.integer  "packagewidth"
    t.integer  "packageweight"
    t.integer  "processorcount"
    t.string   "productgroup"
    t.string   "publisher"
    t.text     "specialfeatures"
    t.string   "studio"
    t.integer  "systemmemorysize"
    t.string   "systemmemorytype"
    t.string   "warranty"
    t.float    "ppm"
    t.float    "ttp"
    t.string   "resolution"
    t.string   "duplex"
    t.string   "connectivity"
    t.string   "papersize"
    t.integer  "paperoutput"
    t.string   "dimensions"
    t.integer  "dutycycle"
    t.integer  "paperinput"
    t.string   "special"
    t.float    "ppmcolor"
    t.string   "platform"
    t.boolean  "colorprinter"
    t.boolean  "scanner"
    t.datetime "scrapedat"
    t.boolean  "nodetails"
    t.boolean  "printserver"
    t.integer  "resolutionmax"
    t.boolean  "fax"
    t.boolean  "bw"
    t.integer  "resolutionarea"
    t.integer  "product_id"
    t.string   "product_type",                    :default => "Printer"
  end

  create_table "amazon_cartridges", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "brand"
    t.string   "model"
    t.string   "mpn"
    t.string   "asin"
    t.integer  "product_id"
    t.text     "detailpageurl"
    t.string   "yieldstr"
    t.integer  "yield"
    t.string   "shelflifestr"
    t.integer  "shelflife"
    t.string   "color"
    t.string   "brandnameprice"
    t.integer  "brandnamepriceint"
    t.text     "compatible"
    t.string   "listprice"
    t.integer  "listpriceint"
    t.text     "imageurl"
    t.text     "title"
    t.integer  "price"
    t.string   "pricestr"
    t.boolean  "iseligibleforsupersavershipping"
    t.integer  "bestoffer"
    t.string   "pricehistory"
    t.string   "imagesurl"
    t.integer  "imagesheight"
    t.integer  "imageswidth"
    t.string   "imagemurl"
    t.integer  "imagemheight"
    t.integer  "imagemwidth"
    t.string   "imagelurl"
    t.integer  "imagelheight"
    t.integer  "imagelwidth"
    t.boolean  "instock"
    t.float    "averagereviewrating"
    t.integer  "totalreviews"
    t.string   "dimensions"
    t.integer  "itemwidth"
    t.integer  "itemlength"
    t.integer  "itemheight"
    t.integer  "packageheight"
    t.integer  "packagelength"
    t.integer  "packagewidth"
    t.integer  "packageweight"
    t.string   "warranty"
    t.text     "manufacturerproducturl"
    t.string   "product_type"
    t.integer  "retailer_id"
    t.string   "region"
    t.string   "merchant"
    t.string   "saleprice"
    t.string   "yousave"
    t.datetime "priceUpdate"
    t.integer  "shippingCost"
    t.integer  "tax"
    t.string   "state"
    t.boolean  "stock"
    t.boolean  "toolow"
    t.string   "availability"
    t.datetime "availabilityUpdate"
    t.text     "url"
    t.boolean  "active"
    t.datetime "activeUpdate"
    t.boolean  "freeShipping"
    t.boolean  "real"
    t.boolean  "toner"
    t.string   "condition"
    t.string   "realbrand"
    t.string   "compatiblebrand"
    t.integer  "offering_id"
    t.datetime "scrapedat"
    t.integer  "numberofitems"
    t.text     "specialfeatures"
  end

  create_table "amazon_groups", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean  "processed",          :default => false
    t.string   "url"
    t.string   "brand"
    t.string   "megapixels_range"
    t.string   "opticalZoom_range"
    t.string   "displaySize_range"
    t.string   "imageStabilization"
    t.string   "viewfinderType"
    t.boolean  "leaf",               :default => false
    t.datetime "scrapedAt"
  end

  create_table "amazon_printers", :force => true do |t|
    t.text     "title"
    t.integer  "price"
    t.string   "pricestr"
    t.boolean  "iseligibleforsupersavershipping"
    t.integer  "bestoffer"
    t.string   "pricehistory"
    t.string   "imagesurl"
    t.integer  "imagesheight"
    t.integer  "imageswidth"
    t.string   "imagemurl"
    t.integer  "imagemheight"
    t.integer  "imagemwidth"
    t.string   "imagelurl"
    t.integer  "imagelheight"
    t.integer  "imagelwidth"
    t.boolean  "instock"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "asin"
    t.text     "detailpageurl"
    t.string   "binding"
    t.string   "brand"
    t.string   "color"
    t.string   "cpumanufacturer"
    t.float    "cpuspeed"
    t.string   "cputype"
    t.float    "displaysize"
    t.string   "ean"
    t.text     "feature"
    t.string   "graphicsmemorysize"
    t.boolean  "isautographed"
    t.boolean  "ismemorabilia"
    t.integer  "itemheight"
    t.integer  "itemlength"
    t.integer  "itemwidth"
    t.integer  "itemweight"
    t.string   "label"
    t.string   "language"
    t.string   "legaldisclaimer"
    t.string   "listpricestr"
    t.integer  "listpriceint"
    t.string   "manufacturer"
    t.string   "model"
    t.string   "modemdescription"
    t.string   "mpn"
    t.string   "nativeresolution"
    t.integer  "numberofitems"
    t.integer  "packageheight"
    t.integer  "packagelength"
    t.integer  "packagewidth"
    t.integer  "packageweight"
    t.integer  "processorcount"
    t.string   "productgroup"
    t.string   "publisher"
    t.text     "specialfeatures"
    t.string   "studio"
    t.integer  "systemmemorysize"
    t.string   "systemmemorytype"
    t.string   "warranty"
    t.float    "ppm"
    t.float    "ttp"
    t.string   "resolution"
    t.string   "duplex"
    t.string   "connectivity"
    t.string   "papersize"
    t.integer  "paperoutput"
    t.string   "dimensions"
    t.integer  "dutycycle"
    t.integer  "paperinput"
    t.string   "special"
    t.float    "ppmcolor"
    t.string   "platform"
    t.boolean  "colorprinter"
    t.boolean  "scanner"
    t.datetime "scrapedat"
    t.boolean  "nodetails"
    t.boolean  "printserver"
    t.integer  "resolutionmax"
    t.boolean  "fax"
    t.boolean  "bw"
    t.integer  "resolutionarea"
    t.integer  "product_id"
    t.string   "product_type",                    :default => "Printer"
    t.float    "averagereviewrating"
    t.integer  "totalreviews"
    t.string   "region",                          :default => "us"
  end

  create_table "bin_specs", :force => true do |t|
    t.integer  "product_id"
    t.string   "name"
    t.boolean  "value"
    t.string   "product_type"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "bin_specs", ["product_id"], :name => "index_bin_specs_on_product_id"

  create_table "boostexter_rules", :force => true do |t|
    t.string   "fieldname"
    t.float    "weight"
    t.integer  "cluster_id"
    t.integer  "version"
    t.text     "yaml_repr"
    t.string   "rule_type"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "camera_reviewcounts", :force => true do |t|
    t.integer "cluster_id",        :limit => 8, :null => false
    t.integer "parent_cluster_id", :limit => 8, :null => false
    t.string  "word",                           :null => false
    t.integer "numchildren",                    :null => false
    t.integer "version",                        :null => false
    t.integer "count",             :limit => 8, :null => false
  end

  add_index "camera_reviewcounts", ["cluster_id", "version", "word"], :name => "cluster_id", :unique => true

  create_table "camera_reviewtotalcounts", :force => true do |t|
    t.integer "cluster_id",        :limit => 8, :null => false
    t.integer "parent_cluster_id", :limit => 8, :null => false
    t.integer "totalcount",        :limit => 8, :null => false
    t.integer "numchildren",                    :null => false
    t.integer "version",                        :null => false
  end

  add_index "camera_reviewtotalcounts", ["cluster_id", "version"], :name => "cluster_id", :unique => true

  create_table "camera_usecase_cluster_scores", :force => true do |t|
    t.integer "usecase_id",              :null => false
    t.float   "score",                   :null => false
    t.integer "cluster_id", :limit => 8, :null => false
    t.integer "version",                 :null => false
  end

  create_table "camera_usecases", :force => true do |t|
    t.string "label", :null => false
  end

  add_index "camera_usecases", ["label"], :name => "label", :unique => true

  create_table "camera_usecases_direct_indicator_words", :force => true do |t|
    t.integer "usecase_id", :null => false
    t.integer "word_id",    :null => false
  end

  add_index "camera_usecases_direct_indicator_words", ["usecase_id", "word_id"], :name => "usecase_id", :unique => true
  add_index "camera_usecases_direct_indicator_words", ["word_id"], :name => "word_id_refs_id_fed99dad"

  create_table "camera_usecases_indicator_words", :force => true do |t|
    t.integer "usecase_id", :null => false
    t.integer "word_id",    :null => false
  end

  add_index "camera_usecases_indicator_words", ["usecase_id", "word_id"], :name => "usecase_id", :unique => true
  add_index "camera_usecases_indicator_words", ["word_id"], :name => "word_id_refs_id_68ebca26"

  create_table "camera_wordcounts", :force => true do |t|
    t.integer "cluster_id",        :limit => 8, :null => false
    t.integer "parent_cluster_id", :limit => 8, :null => false
    t.string  "word",                           :null => false
    t.integer "numchildren",                    :null => false
    t.integer "version",                        :null => false
    t.integer "count",             :limit => 8, :null => false
  end

  add_index "camera_wordcounts", ["cluster_id", "version", "word"], :name => "cluster_id", :unique => true

  create_table "camera_wordtotalcounts", :force => true do |t|
    t.integer "cluster_id",        :limit => 8, :null => false
    t.integer "parent_cluster_id", :limit => 8, :null => false
    t.integer "totalcount",        :limit => 8, :null => false
    t.integer "numchildren",                    :null => false
    t.integer "version",                        :null => false
  end

  add_index "camera_wordtotalcounts", ["cluster_id", "version"], :name => "cluster_id", :unique => true

  create_table "cameras", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "title"
    t.string   "imagesurl"
    t.integer  "imagesheight"
    t.integer  "imageswidth"
    t.string   "imagemurl"
    t.integer  "imagemheight"
    t.integer  "imagemwidth"
    t.string   "imagelurl"
    t.integer  "imagelheight"
    t.integer  "imagelwidth"
    t.text     "detailpageurl"
    t.text     "manufacturerurl"
    t.string   "brand"
    t.string   "model"
    t.string   "mpn"
    t.string   "dimensions"
    t.integer  "itemwidth"
    t.integer  "itemlength"
    t.integer  "itemheight"
    t.integer  "itemweight"
    t.integer  "packageheight"
    t.integer  "packagelength"
    t.integer  "packagewidth"
    t.integer  "packageweight"
    t.float    "opticalzoom"
    t.float    "maximumresolution"
    t.string   "resolution"
    t.float    "displaysize"
    t.boolean  "slr"
    t.boolean  "waterproof"
    t.float    "maximumfocallength"
    t.float    "minimumfocallength"
    t.float    "digitalzoom"
    t.boolean  "batteriesincluded"
    t.string   "batterydescription"
    t.string   "connectivity"
    t.boolean  "hasredeyereduction"
    t.string   "includedsoftware"
    t.float    "averagereviewrating"
    t.integer  "totalreviews"
    t.text     "reviewtext"
    t.integer  "price"
    t.string   "pricestr"
    t.boolean  "instock"
    t.string   "pricehistory"
    t.integer  "price_ca"
    t.string   "price_ca_str"
    t.boolean  "instock_ca"
    t.integer  "bestoffer_ca"
    t.integer  "bestoffer"
  end

  add_index "cameras", ["instock"], :name => "instock"

  create_table "cartridges", :force => true do |t|
    t.string   "brand"
    t.string   "model"
    t.string   "mpn"
    t.string   "compatiblebrand"
    t.integer  "yield"
    t.integer  "shelflife"
    t.string   "color"
    t.string   "brandnameprice"
    t.integer  "brandnamepriceint"
    t.text     "imageurl"
    t.text     "title"
    t.integer  "price"
    t.string   "pricestr"
    t.boolean  "iseligibleforsupersavershipping"
    t.integer  "bestoffer"
    t.string   "pricehistory"
    t.string   "imagesurl"
    t.integer  "imagesheight"
    t.integer  "imageswidth"
    t.string   "imagemurl"
    t.integer  "imagemheight"
    t.integer  "imagemwidth"
    t.string   "imagelurl"
    t.integer  "imagelheight"
    t.integer  "imagelwidth"
    t.boolean  "instock"
    t.float    "averagereviewrating"
    t.integer  "totalreviews"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "dimensions"
    t.integer  "itemwidth"
    t.integer  "itemlength"
    t.integer  "itemheight"
    t.integer  "packageheight"
    t.integer  "packagelength"
    t.integer  "packagewidth"
    t.integer  "packageweight"
    t.float    "costperyield"
    t.string   "condition"
    t.boolean  "real"
    t.string   "warranty"
    t.text     "manufacturerproducturl"
    t.datetime "scrapedat"
    t.boolean  "instock_ca"
    t.integer  "price_ca"
    t.string   "price_ca_str"
  end

  create_table "cat_specs", :force => true do |t|
    t.integer  "product_id"
    t.string   "name"
    t.string   "value"
    t.string   "product_type"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "cat_specs", ["name", "product_type"], :name => "name_2"
  add_index "cat_specs", ["name", "value", "product_type"], :name => "name_3"
  add_index "cat_specs", ["name"], :name => "name"
  add_index "cat_specs", ["product_id"], :name => "index_cat_specs_on_product_id"
  add_index "cat_specs", ["product_type"], :name => "product_type"
  add_index "cat_specs", ["value"], :name => "value"

  create_table "clusters", :force => true do |t|
    t.string  "product_type"
    t.integer "version"
    t.integer "layer"
    t.integer "parent_id"
  end

  create_table "compatibilities", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "accessory_id"
    t.string   "accessory_type"
    t.integer  "product_id"
    t.string   "product_type"
  end

  create_table "cont_specs", :force => true do |t|
    t.integer  "product_id"
    t.string   "name"
    t.float    "value"
    t.string   "product_type"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "cont_specs", ["name", "value", "product_type"], :name => "name_3"
  add_index "cont_specs", ["name", "value"], :name => "name_2"
  add_index "cont_specs", ["name"], :name => "name"
  add_index "cont_specs", ["product_id"], :name => "index_cont_specs_on_product_id"
  add_index "cont_specs", ["value"], :name => "value"

  create_table "db_features", :force => true do |t|
    t.string   "product_type"
    t.string   "feature_type"
    t.string   "name"
    t.float    "min"
    t.float    "max"
    t.float    "high"
    t.float    "low"
    t.text     "categories"
    t.string   "region"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "db_properties", :force => true do |t|
    t.string   "name"
    t.text     "brands"
    t.float    "price_min"
    t.float    "price_max"
    t.float    "price_low"
    t.float    "price_high"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "factors", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "product_type"
    t.integer  "product_id"
    t.string   "cont_var"
    t.float    "value"
    t.integer  "version",      :default => 0, :null => false
  end

  create_table "feature_requests", :force => true do |t|
    t.string   "name"
    t.string   "email"
    t.boolean  "anonymous"
    t.text     "content"
    t.integer  "session_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "floorings", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "title"
    t.text     "brand"
    t.text     "species"
    t.text     "feature"
    t.text     "colorrange"
    t.float    "width"
    t.integer  "price"
    t.string   "pricestr"
    t.float    "regularprice"
    t.integer  "miniorder_sq_ft"
    t.integer  "miniorder"
    t.text     "price_unit"
    t.string   "warranty"
    t.float    "thickness"
    t.text     "size"
    t.string   "finish"
    t.float    "profit_margin"
    t.float    "overallrating"
    t.string   "aggregate_desc"
    t.boolean  "instock"
  end

  create_table "grabber_cartridges", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "item_number"
    t.text     "detailpageurl"
    t.text     "image"
    t.string   "pricestr"
    t.string   "title"
    t.string   "availability"
    t.string   "printermodel"
    t.string   "printerbrand"
    t.integer  "printerid"
    t.string   "printerids"
  end

  create_table "grabber_offerings", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "product_id"
    t.integer  "offering_id"
    t.string   "item_number"
  end

  create_table "keyword_searches", :force => true do |t|
    t.string  "keyword"
    t.integer "product_id"
  end

  add_index "keyword_searches", ["keyword"], :name => "index_keyword_searches_on_keyword"

  create_table "newegg_offerings", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "printer_id"
    t.string   "item_number"
    t.integer  "product_id"
    t.string   "product_type"
    t.integer  "offering_id"
    t.integer  "retailer_id"
    t.integer  "priceint"
    t.string   "pricestr"
    t.boolean  "toolow"
    t.datetime "priceUpdate"
    t.boolean  "stock"
    t.string   "availability"
    t.datetime "availabilityUpdate"
    t.boolean  "active"
    t.datetime "activeUpdate"
    t.boolean  "freeShipping"
    t.text     "url"
  end

  create_table "newegg_printer_scraped_datas", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "item_number"
    t.string   "manufacturer"
    t.string   "series"
    t.string   "brand"
    t.boolean  "toolow"
    t.float    "saleprice"
    t.float    "listprice"
    t.string   "imageurl"
    t.boolean  "recertified"
    t.boolean  "openbox"
    t.string   "shipping"
    t.string   "title"
    t.string   "manufacturerproducturl"
    t.string   "stock"
    t.string   "model"
    t.string   "recommendeduse"
    t.string   "dimensions"
    t.integer  "weight"
    t.string   "outputtype"
    t.string   "lasertechnology"
    t.float    "blackprintspeed"
    t.float    "colorprintspeed"
    t.float    "timetofirstpageseconds"
    t.string   "blackprintquality"
    t.string   "colorprintquality"
    t.string   "printlanguagesstd"
    t.string   "duplexprinting"
    t.integer  "maxdutycycle"
    t.string   "papertraysstd"
    t.string   "papertraysmax"
    t.integer  "inputcapacitystd"
    t.integer  "inputcapacitymax"
    t.integer  "outputcapacitystd"
    t.integer  "outputcapacitymax"
    t.string   "mediatype"
    t.string   "mediasizessupported"
    t.string   "usbports"
    t.string   "lptports"
    t.string   "networkports"
    t.string   "otherports"
    t.string   "microprocessortype"
    t.string   "processormhz"
    t.string   "memorystd"
    t.string   "memorymax"
    t.string   "cartridgescompatible"
    t.string   "powerrequirements"
    t.string   "powerconsumption"
    t.string   "windowscompatible"
    t.string   "macintoshcompatible"
    t.string   "parts"
    t.string   "labor"
    t.string   "copyqualityblack"
    t.string   "scanresolutionenhanced"
    t.string   "windowsvista"
    t.string   "other"
    t.string   "faxfeatures"
    t.string   "noiselevelapprox"
    t.string   "modemspeed"
    t.string   "emulations"
    t.string   "comports"
    t.string   "display"
    t.string   "copyspeedblack"
    t.string   "maxdocumentenlargement"
    t.string   "maxdocumentreduction"
    t.string   "maxnumberofcopies"
    t.string   "scancolordepth"
    t.string   "scanresolutionoptical"
    t.string   "packagecontents"
    t.string   "faxmemory"
    t.string   "copyspeedcolor"
    t.string   "faxtransmissionspeed"
    t.string   "scanelement"
    t.string   "faxresolutions"
    t.string   "softwareincluded"
    t.string   "connectivitytechnology"
    t.string   "colorfax"
    t.string   "copyqualitycolor"
    t.string   "borderlessphotosizes"
    t.string   "scanresolutionhardware"
  end

  create_table "newegg_printers", :force => true do |t|
    t.string   "item_number"
    t.integer  "product_id"
    t.string   "product_type"
    t.string   "model"
    t.string   "series"
    t.string   "brand"
    t.integer  "listpriceint"
    t.string   "listpricestr"
    t.string   "imageurl"
    t.text     "detailpageurl"
    t.string   "recommendeduse"
    t.string   "dimensions"
    t.integer  "itemheight"
    t.integer  "itemwidth"
    t.integer  "itemlength"
    t.integer  "itemweight"
    t.boolean  "colorprinter"
    t.boolean  "printserver"
    t.boolean  "scanner"
    t.datetime "scrapedat"
    t.string   "lasertechnology"
    t.string   "platform"
    t.string   "warranty"
    t.float    "ppm"
    t.float    "ppmcolor"
    t.float    "ttp"
    t.string   "resolution"
    t.string   "language"
    t.string   "duplex"
    t.integer  "dutycycle"
    t.integer  "paperinput"
    t.integer  "paperinputmax"
    t.integer  "paperoutput"
    t.integer  "paperoutputmax"
    t.string   "systemmemory"
    t.string   "systemmemorymax"
    t.string   "mediatype"
    t.string   "papersize"
    t.string   "cputype"
    t.float    "cpuspeed"
    t.string   "connectivity"
    t.string   "special"
    t.string   "usbports"
    t.string   "lptports"
    t.string   "networkports"
    t.string   "otherports"
    t.string   "comports"
    t.string   "copyspeedblack"
    t.string   "copyspeedcolor"
    t.string   "copyqualityblack"
    t.string   "copyqualitycolor"
    t.string   "maxnumberofcopies"
    t.string   "scanresolutionenhanced"
    t.string   "maxdocumentenlargement"
    t.string   "maxdocumentreduction"
    t.string   "scancolordepth"
    t.string   "scanresolutionoptical"
    t.string   "scanresolutionhardware"
    t.string   "scanelement"
    t.string   "faxfeatures"
    t.string   "faxmemory"
    t.string   "faxtransmissionspeed"
    t.string   "colorfax"
    t.string   "faxresolutions"
    t.string   "noiselevelapprox"
    t.string   "modemspeed"
    t.string   "emulations"
    t.string   "display"
    t.string   "packagecontents"
    t.string   "softwareincluded"
    t.string   "borderlessphotosizes"
    t.string   "colorresolution"
    t.string   "papertraysstd"
    t.string   "papertraysmax"
    t.string   "cartridgescompatible"
    t.string   "powerrequirements"
    t.string   "powerconsumption"
    t.integer  "resolutionmax"
    t.string   "title"
    t.string   "region",                 :default => "us"
    t.string   "mpn"
  end

  create_table "nodes", :force => true do |t|
    t.integer "cluster_id"
    t.integer "product_id"
    t.string  "product_type"
    t.integer "version"
  end

  add_index "nodes", ["cluster_id"], :name => "cluster_id"
  add_index "nodes", ["product_id"], :name => "product_id"
  add_index "nodes", ["product_type"], :name => "product_type"
  add_index "nodes", ["version"], :name => "version"

  create_table "one23_cartridges", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "product_id"
    t.string   "brand"
    t.string   "model"
    t.string   "mpn"
    t.integer  "web_id"
    t.text     "detailpageurl"
    t.string   "yieldstr"
    t.integer  "yield"
    t.string   "shelflifestr"
    t.integer  "shelflife"
    t.string   "color"
    t.string   "brandnameprice"
    t.integer  "brandnamepriceint"
    t.text     "compatible"
    t.string   "listprice"
    t.integer  "listpriceint"
    t.text     "imageurl"
    t.text     "instructionsurl"
    t.text     "title"
    t.integer  "price"
    t.string   "pricestr"
    t.boolean  "iseligibleforsupersavershipping"
    t.integer  "bestoffer"
    t.string   "pricehistory"
    t.string   "imagesurl"
    t.integer  "imagesheight"
    t.integer  "imageswidth"
    t.string   "imagemurl"
    t.integer  "imagemheight"
    t.integer  "imagemwidth"
    t.string   "imagelurl"
    t.integer  "imagelheight"
    t.integer  "imagelwidth"
    t.boolean  "instock"
    t.float    "averagereviewrating"
    t.integer  "totalreviews"
    t.string   "dimensions"
    t.integer  "itemwidth"
    t.integer  "itemlength"
    t.integer  "itemheight"
    t.integer  "packageheight"
    t.integer  "packagelength"
    t.integer  "packagewidth"
    t.integer  "packageweight"
    t.string   "warranty"
    t.text     "manufacturerproducturl"
    t.string   "product_type"
    t.integer  "retailer_id"
    t.string   "region"
    t.string   "merchant"
    t.string   "saleprice"
    t.string   "yousave"
    t.datetime "priceUpdate"
    t.integer  "shippingCost"
    t.integer  "tax"
    t.string   "state"
    t.boolean  "stock"
    t.boolean  "toolow"
    t.string   "availability"
    t.datetime "availabilityUpdate"
    t.text     "url"
    t.boolean  "active"
    t.datetime "activeUpdate"
    t.boolean  "freeShipping"
    t.datetime "scrapedat"
    t.boolean  "ink"
    t.string   "condition"
    t.boolean  "real"
    t.integer  "offering_id"
  end

  create_table "preference_relations", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "session_id"
    t.integer  "lower"
    t.integer  "higher"
    t.float    "weight"
  end

  create_table "preferences", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "prefname"
    t.float    "prefval"
    t.integer  "sessionid"
    t.integer  "searchid"
    t.string   "producttype"
  end

  create_table "prefs", :id => false, :force => true do |t|
    t.integer  "id",                            :default => 0, :null => false
    t.integer  "idvisit"
    t.string   "idcookie",        :limit => 32
    t.integer  "product_picked"
    t.integer  "product_ignored"
    t.float    "weight"
    t.float    "slider_min"
    t.float    "slider_max"
    t.string   "slider_name",     :limit => 40
    t.string   "search_text"
    t.integer  "search_numtimes", :limit => 2
    t.datetime "servertime"
    t.integer  "optemo_session"
    t.integer  "filter_type",     :limit => 2
    t.integer  "idsite"
  end

  create_table "printers", :force => true do |t|
    t.string   "brand"
    t.float    "displaysize"
    t.string   "ean"
    t.text     "feature"
    t.integer  "itemheight"
    t.integer  "itemlength"
    t.integer  "itemwidth"
    t.integer  "itemweight"
    t.integer  "listpriceint"
    t.string   "model"
    t.string   "mpn"
    t.integer  "packageheight"
    t.integer  "packagelength"
    t.integer  "packagewidth"
    t.integer  "packageweight"
    t.text     "title"
    t.string   "warranty"
    t.integer  "price"
    t.string   "pricestr"
    t.boolean  "iseligibleforsupersavershipping"
    t.string   "imagesurl"
    t.integer  "imagesheight"
    t.integer  "imageswidth"
    t.string   "imagemurl"
    t.integer  "imagemheight"
    t.integer  "imagemwidth"
    t.string   "imagelurl"
    t.integer  "imagelheight"
    t.integer  "imagelwidth"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.float    "ppm"
    t.float    "ttp"
    t.string   "resolution"
    t.string   "duplex"
    t.string   "connectivity"
    t.string   "papersize"
    t.integer  "paperoutput"
    t.string   "dimensions"
    t.integer  "dutycycle"
    t.integer  "paperinput"
    t.string   "special"
    t.float    "ppmcolor"
    t.string   "platform"
    t.boolean  "colorprinter"
    t.boolean  "scanner"
    t.datetime "scrapedat"
    t.boolean  "nodetails"
    t.boolean  "printserver"
    t.boolean  "instock"
    t.string   "pricehistory"
    t.integer  "bestoffer"
    t.integer  "resolutionarea"
    t.integer  "resolutionmax"
    t.string   "manufacturerproducturl"
    t.float    "averagereviewrating"
    t.integer  "totalreviews"
    t.integer  "price_ca"
    t.string   "price_ca_str"
    t.boolean  "instock_ca"
    t.integer  "bestoffer_ca"
  end

  create_table "products", :force => true do |t|
    t.string   "product_type"
    t.string   "title"
    t.string   "model"
    t.string   "mpn"
    t.boolean  "instock"
    t.string   "imgsurl"
    t.integer  "imgsh"
    t.integer  "imgsw"
    t.string   "imgmurl"
    t.integer  "imgmh"
    t.integer  "imgmw"
    t.string   "imglurl"
    t.integer  "imglh"
    t.integer  "imglw"
    t.float    "avgreviewrating"
    t.integer  "totalreviews"
    t.string   "manufacturerurl"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "url"
  end

  add_index "products", ["instock"], :name => "instock"
  add_index "products", ["product_type"], :name => "product_type"

  create_table "referrals", :force => true do |t|
    t.integer  "product_id"
    t.string   "product_type"
    t.integer  "session_id"
    t.integer  "retailer_offering_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "retailer_offerings", :force => true do |t|
    t.integer  "product_id"
    t.string   "product_type"
    t.integer  "priceint"
    t.string   "pricestr"
    t.integer  "tax"
    t.string   "state"
    t.integer  "retailer_id"
    t.boolean  "stock"
    t.string   "pricehistory"
    t.boolean  "toolow"
    t.string   "availability"
    t.boolean  "iseligibleforsupersavershipping"
    t.string   "merchant"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.float    "shippingCost"
    t.boolean  "freeShipping"
    t.datetime "priceUpdate"
    t.datetime "availabilityUpdate"
    t.boolean  "active"
    t.datetime "activeUpdate"
    t.string   "region",                          :default => "us"
    t.string   "condition",                       :default => "New"
    t.string   "local_id"
    t.float    "price"
  end

  add_index "retailer_offerings", ["product_id", "product_type", "region"], :name => "product_id"

  create_table "retailers", :force => true do |t|
    t.string   "url"
    t.string   "name"
    t.string   "image"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "region",        :default => "us"
    t.string   "local_id_name"
  end

  create_table "reviews", :force => true do |t|
    t.string   "product_type"
    t.integer  "product_id"
    t.integer  "rating"
    t.integer  "helpfulvotes"
    t.datetime "date"
    t.string   "customerid"
    t.integer  "totalvotes"
    t.text     "content"
    t.string   "source"
    t.string   "summary"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "local_id"
    t.string   "local_review_id"
    t.integer  "retailer_id"
    t.text     "review_url"
    t.text     "pros"
    t.text     "cons"
    t.float    "value_rating"
  end

  add_index "reviews", ["product_type", "product_id"], :name => "product_type"

  create_table "saveds", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "session_id"
    t.integer  "product_id"
    t.integer  "search_id"
    t.string   "product_type"
  end

  create_table "scraped_cameras", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "title"
    t.text     "imageurl"
    t.text     "detailpageurl"
    t.text     "manufacturerurl"
    t.datetime "scrapedat"
    t.string   "brand"
    t.string   "model"
    t.string   "mpn"
    t.string   "dimensions"
    t.integer  "itemwidth"
    t.integer  "itemlength"
    t.integer  "itemheight"
    t.integer  "itemweight"
    t.integer  "packageheight"
    t.integer  "packagelength"
    t.integer  "packagewidth"
    t.integer  "packageweight"
    t.float    "opticalzoom"
    t.string   "resolution"
    t.float    "displaysize"
    t.boolean  "slr"
    t.boolean  "waterproof"
    t.float    "maximumfocallength"
    t.float    "minimumfocallength"
    t.float    "digitalzoom"
    t.boolean  "batteriesincluded"
    t.string   "batterydescription"
    t.string   "connectivity"
    t.boolean  "hasredeyereduction"
    t.string   "includedsoftware"
    t.float    "averagereviewrating"
    t.integer  "totalreviews"
    t.text     "reviewtext"
    t.integer  "product_id"
    t.integer  "retailer_id"
    t.string   "local_id"
    t.boolean  "aa_batteries"
    t.boolean  "bodyonly"
    t.float    "maximumresolution"
  end

  create_table "scraped_cartridges", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "scraped_lph_printers", :force => true do |t|
    t.text     "title"
    t.string   "imagesurl"
    t.integer  "imagesheight"
    t.integer  "imageswidth"
    t.string   "imagemurl"
    t.integer  "imagemheight"
    t.integer  "imagemwidth"
    t.string   "imagelurl"
    t.integer  "imagelheight"
    t.integer  "imagelwidth"
    t.integer  "price"
    t.string   "pricestr"
    t.boolean  "instock"
    t.integer  "bestoffer",                       :limit => 1
    t.string   "pricehistory"
    t.integer  "price_ca"
    t.string   "price_ca_str"
    t.boolean  "instock_ca"
    t.boolean  "bestoffer_ca"
    t.boolean  "iseligibleforsupersavershipping"
    t.float    "averagereviewrating"
    t.integer  "totalreviews"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "dimensions"
    t.integer  "itemwidth"
    t.integer  "itemlength"
    t.integer  "itemheight"
    t.integer  "itemweight"
    t.integer  "packageheight"
    t.integer  "packagelength"
    t.integer  "packagewidth"
    t.integer  "packageweight"
    t.string   "brand"
    t.string   "model"
    t.string   "mpn"
    t.float    "ppm"
    t.string   "resolution"
    t.integer  "resolutionmax"
    t.integer  "paperinput"
    t.boolean  "scanner"
    t.boolean  "printserver"
    t.float    "displaysize"
    t.float    "ttp"
    t.string   "duplex"
    t.boolean  "colorprinter"
    t.boolean  "fax"
    t.string   "papersize"
    t.integer  "paperoutput"
    t.string   "connectivity"
    t.integer  "dutycycle"
    t.string   "special"
    t.float    "ppmcolor"
    t.string   "platform"
    t.string   "ean"
    t.text     "feature"
    t.integer  "listpriceint"
    t.string   "warranty"
    t.datetime "scrapedat"
    t.boolean  "nodetails"
    t.boolean  "bw"
    t.string   "manufacturerproducturl"
    t.integer  "product_id"
    t.integer  "retailer_id"
    t.string   "local_id"
    t.text     "imageurl"
  end

  create_table "scraped_printers", :force => true do |t|
    t.text     "title"
    t.integer  "price"
    t.string   "pricestr"
    t.boolean  "iseligibleforsupersavershipping"
    t.integer  "bestoffer"
    t.string   "pricehistory"
    t.string   "imagesurl"
    t.integer  "imagesheight"
    t.integer  "imageswidth"
    t.string   "imagemurl"
    t.integer  "imagemheight"
    t.integer  "imagemwidth"
    t.string   "imagelurl"
    t.integer  "imagelheight"
    t.integer  "imagelwidth"
    t.boolean  "instock"
    t.float    "averagereviewrating"
    t.integer  "totalreviews"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "dimensions"
    t.integer  "itemwidth"
    t.integer  "itemlength"
    t.integer  "itemheight"
    t.integer  "itemweight"
    t.integer  "packageheight"
    t.integer  "packagelength"
    t.integer  "packagewidth"
    t.integer  "packageweight"
    t.string   "brand"
    t.float    "displaysize"
    t.string   "ean"
    t.text     "feature"
    t.integer  "listpriceint"
    t.string   "model"
    t.string   "mpn"
    t.string   "warranty"
    t.float    "ppm"
    t.float    "ttp"
    t.string   "resolution"
    t.string   "duplex"
    t.string   "connectivity"
    t.string   "papersize"
    t.integer  "paperoutput"
    t.integer  "dutycycle"
    t.integer  "paperinput"
    t.string   "special"
    t.float    "ppmcolor"
    t.string   "platform"
    t.boolean  "colorprinter"
    t.boolean  "scanner"
    t.datetime "scrapedat"
    t.boolean  "nodetails"
    t.boolean  "printserver"
    t.integer  "resolutionmax"
    t.boolean  "fax"
    t.boolean  "bw"
    t.string   "manufacturerproducturl"
    t.integer  "product_id"
    t.integer  "retailer_id"
    t.string   "local_id"
    t.text     "imageurl"
  end

  create_table "search_products", :force => true do |t|
    t.integer "search_id"
    t.integer "product_id"
  end

  add_index "search_products", ["search_id"], :name => "index_search_products_on_search_id"

  create_table "searches", :force => true do |t|
    t.integer  "session_id"
    t.string   "keyword_search"
    t.integer  "page"
    t.string   "groupby"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "sessions", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "ip"
    t.integer  "parent_id"
    t.string   "product_type"
    t.boolean  "filter"
    t.string   "region",       :default => "us"
  end

  create_table "stem_labels", :force => true do |t|
    t.string "label", :null => false
    t.string "stem",  :null => false
  end

  add_index "stem_labels", ["label"], :name => "label", :unique => true
  add_index "stem_labels", ["stem"], :name => "stem", :unique => true

  create_table "surveys", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "session_id"
    t.string   "firstname"
    t.string   "lastname"
    t.string   "rating"
    t.boolean  "followup"
    t.string   "email"
    t.text     "experience"
    t.text     "improvements"
  end

  create_table "text_specs", :force => true do |t|
    t.integer  "product_id"
    t.string   "name"
    t.text     "value"
    t.string   "product_type"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "tiger_offerings", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "tigerurl"
    t.integer  "offering_id"
    t.integer  "tiger_printer_id"
    t.integer  "priceint"
    t.string   "pricestr"
    t.boolean  "toolow"
    t.boolean  "stock"
    t.string   "region"
    t.text     "url"
    t.string   "condition"
    t.string   "pricehistory"
    t.datetime "priceUpdate"
    t.integer  "shippingCost"
    t.integer  "tax"
    t.string   "state"
    t.string   "availability"
    t.datetime "availabilityUpdate"
    t.boolean  "active"
    t.datetime "activeUpdate"
    t.boolean  "freeShipping"
    t.integer  "retailer_id"
  end

  create_table "tiger_printers", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "title"
    t.string   "brand"
    t.string   "model"
    t.text     "tigerurl"
    t.string   "mpn"
    t.string   "upcno"
    t.integer  "price"
    t.string   "pricestr"
    t.integer  "listpriceint"
    t.string   "listpricestr"
    t.integer  "bestoffer"
    t.boolean  "instock"
    t.integer  "price_ca"
    t.string   "pricestr_ca"
    t.integer  "listpriceint_ca"
    t.string   "listpricestr_ca"
    t.boolean  "instock_ca"
    t.float    "ppm"
    t.integer  "paperinput"
    t.integer  "resolutionmax"
    t.integer  "itemheight"
    t.integer  "itemlength"
    t.integer  "itemwidth"
    t.boolean  "scanner"
    t.boolean  "printserver"
    t.integer  "itemweight"
    t.integer  "packageheight"
    t.integer  "packagelength"
    t.integer  "packagewidth"
    t.integer  "packageweight"
    t.string   "warranty"
    t.float    "ttp"
    t.string   "resolution"
    t.string   "duplex"
    t.string   "connectivity"
    t.string   "papersize"
    t.integer  "paperoutput"
    t.string   "dimensions"
    t.integer  "dutycycle"
    t.float    "ppmcolor"
    t.string   "platform"
    t.boolean  "colorprinter"
    t.datetime "scrapedat"
  end

  create_table "tiger_scrapeds", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "tigerurl"
    t.text     "title"
    t.string   "itemnumber"
    t.string   "model"
    t.string   "region"
    t.string   "manufacturedby"
    t.string   "warrantyprovidedby"
    t.string   "shippingweight"
    t.string   "mfgpartno"
    t.string   "upcno"
    t.string   "boxsize"
    t.string   "availability"
    t.string   "itmdets"
    t.string   "finalprice"
    t.string   "instantsavings"
    t.string   "originalprice"
    t.string   "price"
    t.string   "allinone"
    t.string   "approximatepageyield"
    t.string   "automaticfeeder"
    t.string   "color"
    t.string   "coloroutput"
    t.string   "condition"
    t.string   "connectivity"
    t.string   "dimensions"
    t.string   "duplexprinting"
    t.string   "faxcapability"
    t.string   "firstpageoutputtime"
    t.string   "maximumdutycycle"
    t.string   "memoryincluded"
    t.string   "networkready"
    t.string   "optionalconnectivity"
    t.string   "optionalpaperinput"
    t.string   "papersizessupported"
    t.string   "powersource"
    t.string   "powersupply"
    t.string   "printeruse"
    t.string   "printmethod"
    t.string   "printspeed"
    t.string   "printspeedbw"
    t.string   "printspeedcolor"
    t.string   "printtechnology"
    t.string   "processor"
    t.string   "producttype"
    t.string   "protocols"
    t.string   "quantity"
    t.string   "resolution"
    t.string   "specialfeatures"
    t.string   "standardpaperinput"
    t.string   "standardpaperoutput"
    t.string   "transferrate"
    t.string   "wireless"
  end

  create_table "userdatabins", :force => true do |t|
    t.integer  "search_id"
    t.string   "name"
    t.boolean  "value"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "userdatacats", :force => true do |t|
    t.integer  "search_id"
    t.string   "name"
    t.string   "value"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "userdataconts", :force => true do |t|
    t.integer  "search_id"
    t.string   "name"
    t.float    "min"
    t.float    "max"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "userdataconts", ["search_id"], :name => "search_id"

  create_table "userdatasearches", :force => true do |t|
    t.integer  "search_id"
    t.string   "keyword"
    t.text     "keywordpids"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "userdatasearches", ["search_id"], :name => "index_userdatasearches_on_search_id"

  create_table "users", :force => true do |t|
    t.datetime "created_at"
  end

  create_table "vieweds", :force => true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "session_id"
    t.integer  "product_id"
    t.integer  "search_id"
  end

  create_table "welcomes", :force => true do |t|
    t.string   "email"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
